<!--
function f(fn,ft,fd){
 this.fn=fn;
 this.ft=ft;
 this.fd=fd;
}
var Fs=new Array (
new f("//videos.videomusica.es/aaron-neville.html","Videomúsica sección videos, Aaron Neville","Videomúsica, información y videos. Aaron Neville"),new f("//videos.videomusica.es/Aaron.Neville.html","Videomúsica sección videos, Aaron Neville","Videomúsica, información y videos. Aaron Neville"),new f("//videos.videomusica.es/Abba.html","Videomúsica sección videos, Abba","Videomúsica, información y videos. Abba"),new f("//videos.videomusica.es/ac-dc.html","Videomúsica sección videos, AC/DC","Videomúsica, información y videos. AC/DC"),new f("//videos.videomusica.es/al-green.html","Videomúsica sección videos, Al Green","Videomúsica, información y videos. Al Green"),new f("//videos.videomusica.es/al-jarreau.html","Videomúsica sección videos, Al Jarreau","Videomúsica, información y videos. Al Jarreau"),new f("//videos.videomusica.es/albert-hammond.html","Videomúsica sección videos, Albert Hammond","Videomúsica, información y videos. Albert Hammond"),new f("//videos.videomusica.es/Amaral.html","Videomúsica sección videos, Amaral","Videomúsica, información y videos. Amaral"),new f("//videos.videomusica.es/ana-belen.html","Videomúsica sección videos, Ana Belén","Videomúsica, información y videos. Ana Belén"),new f("//videos.videomusica.es/antonio-vega.html","Videomúsica sección videos, Antonio Vega","Videomúsica, información y videos. Antonio Vega"),
new f("//videos.videomusica.es/baron-rojo.html","Videomúsica sección videos, Barón Rojo","Videomúsica, información y videos. Barón Rojo"),new f("//videos.videomusica.es/barry-white.html","Videomúsica sección videos, Barry White","Videomúsica, información y videos. Barry White"),new f("//videos.videomusica.es/bee-gees.html","Videomúsica sección videos, Bee Gees","Videomúsica, información y videos. Bee Gees"),new f("//videos.videomusica.es/billy-joel.html","Videomúsica sección videos, Billy Joel","Videomúsica, información y videos. Billy Joel"),new f("//videos.videomusica.es/black-eyed-peas.html","Videomúsica sección videos, Black Eyed Peas","Videomúsica, información y videos. Black Eyed Peas"),new f("//videos.videomusica.es/bobby-caldwell.html","Videomúsica sección videos, Bobby Caldwell","Videomúsica, información y videos. Bobby Caldwell"),new f("//videos.videomusica.es/boney-m.html","Videomúsica sección videos, Boney M","Videomúsica, información y videos. Boney M"),new f("//videos.videomusica.es/camilo-sesto.html","Videomúsica sección videos, Camilo Sesto","Videomúsica, información y videos. Camilo Sesto"),new f("//videos.videomusica.es/candi-staton.html","Videomúsica sección videos, Candi Staton","Videomúsica, información y videos. Candi Staton"),new f("//videos.videomusica.es/carole-king.html","Videomúsica sección videos, Carole King","Videomúsica, información y videos. Carole King"),
new f("//videos.videomusica.es/celine-dion.html","Videomúsica sección videos, Céline Dion","Videomúsica, información y videos. Céline Dion"),new f("//videos.videomusica.es/chambao.html","Videomúsica sección videos, Chambao","Videomúsica, información y videos. Chambao"),new f("//videos.videomusica.es/charles-eddie.html","Videomúsica sección videos, Charles & Eddie","Videomúsica, información y videos. Charles & Eddie"),new f("//videos.videomusica.es/david-bowie.html","Videomúsica, David Bowie","Videomúsica, información y videos. David Bowie"),new f("//videos.videomusica.es/dire-straits.html","Videomúsica sección videos, Dire Straits","Videomúsica, información y videos. Dire Straits"),new f("//videos.videomusica.es/donald-fagen.html","Videomúsica sección videos, Donald Fagen","Videomúsica, información y videos. Donald Fagen"),new f("//videos.videomusica.es/Dyango.html","Videomúsica sección videos, Dyango","Videomúsica, información y videos. Dyango"),new f("//videos.videomusica.es/earth-wind-fire.html","Videomúsica sección videos, Earth Wind & Fire","Videomúsica, información y videos. Earth Wind & Fire"),new f("//videos.videomusica.es/elo.html","Videomúsica sección videos, E.L.O. (Electric Light Orchest...","Videomúsica, información y videos. E.L.O. (Electric Light Orchestra)"),new f("//videos.videomusica.es/elton-john.html","Videomúsica sección videos, Elton John","Videomúsica, información y videos. Elton John"),
new f("//videos.videomusica.es/fito-fitipaldis.html","Videomúsica sección videos, Fito & Fitipaldis","Videomúsica, información y videos. Fito & Fitipaldis"),new f("//videos.videomusica.es/fleetwood-mac.html","Videomúsica sección videos, Fleetwood Mac","Videomúsica, información y videos. Fleetwood Mac"),new f("//videos.videomusica.es/george-benson.html","Videomúsica sección videos, George Benson","Videomúsica, información y videos. George Benson"),new f("//videos.videomusica.es/george-michael.html","Videomúsica sección videos, George Michael","Videomúsica, información y videos. George Michael"),new f("//videos.videomusica.es/gladys-knight.html","Videomúsica sección videos, Gladys Knight & the Pips","Videomúsica, información y videos. Gladys Knight & the Pips"),new f("//videos.videomusica.es/Incognito.html","Videomúsica sección videos, Incognito","Videomúsica, información y videos. Incognito"),new f("//videos.videomusica.es/Jamiroquai.html","Videomúsica sección videos, Jamiroquai","Videomúsica, información y videos. Jamiroquai"),new f("//videos.videomusica.es/joaquin-sabina.html","Videomúsica sección videos, Joaquín Sabina","Videomúsica, información y videos. Joaquín Sabina"),new f("//videos.videomusica.es/jose-feliciano.html","Videomúsica sección videos, José Feliciano","Videomúsica, información y videos. José Feliciano"),new f("//videos.videomusica.es/Joss.Stone.html","Videomúsica sección videos, Joss Stone","Videomúsica, información y videos. Joss Stone"),
new f("//videos.videomusica.es/juan-luis-guerra.html","Videomúsica sección videos, Juan Luis Guerra","Videomúsica, información y videos. Juan Luis Guerra"),new f("//videos.videomusica.es/julio-iglesias.html","Videomúsica sección videos, Julio Iglesias","Videomúsica, información y videos. Julio Iglesias"),new f("//videos.videomusica.es/katie-melua.html","Videomúsica sección videos, Katie Melua","Videomúsica, información y videos. Katie Melua"),new f("//videos.videomusica.es/Ketama.html","Videomúsica sección videos, Ketama","Videomúsica, información y videos. Ketama"),new f("//videos.videomusica.es/la-oreja-de-van-gogh.html","Videomúsica sección videos, La Oreja de Van Gogh","Videomúsica, información y videos. La Oreja de Van Gogh"),new f("//videos.videomusica.es/laura-izibor.html","Videomúsica sección videos, Laura Izibor","Videomúsica, información y videos. Laura Izibor"),new f("//videos.videomusica.es/lionel-richie.html","Videomúsica sección videos, Lionel Richie","Videomúsica, información y videos. Lionel Richie"),new f("//videos.videomusica.es/los-modulos.html","Videomúsica sección videos, Los Módulos","Videomúsica, información y videos. Los Módulos"),new f("//videos.videomusica.es/los-panchos.html","Videomúsica sección videos, Los Panchos","Videomúsica, información y videos. Los Panchos"),new f("//videos.videomusica.es/lou-rawls.html","Videomúsica sección videos, Lou Rawls","Videomúsica, información y videos. Lou Rawls"),
new f("//videos.videomusica.es/luis-eduardo-aute.html","Videomúsica sección videos, Luis Eduardo Aute","Videomúsica, información y videos. Luis Eduardo Aute"),new f("//videos.videomusica.es/luis-miguel.html","Videomúsica sección videos, Luis Miguel","Videomúsica, información y videos. Luis Miguel"),new f("//videos.videomusica.es/m-clan.html","Videomúsica sección videos, M-Clan","Videomúsica, información y videos. M-Clan"),new f("//videos.videomusica.es/manolo-garcia.html","Videomúsica sección videos, Manolo García","Videomúsica, información y videos. Manolo García"),new f("//videos.videomusica.es/marc-anthony.html","Videomúsica sección videos, Marc Anthony","Videomúsica, información y videos. Marc Anthony"),new f("//videos.videomusica.es/mariah-carey.html","Videomúsica sección videos, Mariah Carey","Videomúsica, información y videos. Mariah Carey"),new f("//videos.videomusica.es/marvin-gaye.html","Videomúsica sección videos, Marvin Gaye","Videomúsica, información y videos. Marvin Gaye"),new f("//videos.videomusica.es/mary-j-blige.html","Videomúsica sección videos, Mary J. Blige","Videomúsica, información y videos. Mary J. Blige"),new f("//videos.videomusica.es/Mecano.html","Videomúsica sección videos, Mecano","Videomúsica, información y videos. Mecano"),new f("//videos.videomusica.es/miguel-rios.html","Videomúsica sección videos, Miguel Ríos","Videomúsica, información y videos. Miguel Ríos"),
new f("//videos.videomusica.es/Mocedades.html","Videomúsica sección videos, Mocedades","Videomúsica, información y videos. Mocedades"),new f("//videos.videomusica.es/monica-naranjo.html","Videomúsica sección videos, Mónica Naranjo","Videomúsica, información y videos. Mónica Naranjo"),new f("//videos.videomusica.es/natalia-lafourcade.html","Videomúsica sección videos, Natalia Lafourcade","Videomúsica, información y videos. Natalia Lafourcade"),new f("//videos.videomusica.es/nino-bravo.html","Videomúsica sección videos, Aaron Neville","Videomúsica, información y videos. Aaron Neville"),new f("//videos.videomusica.es/oleta-adams.html","Videomúsica sección videos, Oleta Adams","Videomúsica, información y videos. Oleta Adams"),new f("//videos.videomusica.es/otis-redding.html","Videomúsica sección videos, Otis Redding","Videomúsica, información y videos. Otis Redding"),new f("//videos.videomusica.es/paul-carrack.html","Videomúsica sección videos, Paul Carrack","Videomúsica, información y videos. Paul Carrack"),new f("//videos.videomusica.es/pet-shop-boys.html","Videomúsica sección videos, Pet Shop Boys","Videomúsica, información y videos. Pet Shop Boys"),new f("//videos.videomusica.es/pink-floyd.html","Videomúsica sección videos, Pink Floyd","Videomúsica, información y videos. Pink Floyd"),new f("//videos.videomusica.es/Prince.html","Videomúsica sección videos, Prince","Videomúsica, información y videos. Prince-The Artist"),
new f("//videos.videomusica.es/Queen.html","Videomúsica sección videos, Queen","Videomúsica, información y videos. Queen"),new f("//videos.videomusica.es/radio-futura.html","Videomúsica sección videos, Radio Futura","Videomúsica, información y videos. Radio Futura"),new f("//videos.videomusica.es/Raphael.html","Videomúsica sección videos, Raphael","Videomúsica, información y videos. Raphael"),new f("//videos.videomusica.es/Rem.html","Videomúsica sección videos, R.E.M.","Videomúsica, información y videos. R.E.M."),new f("//videos.videomusica.es/Rico.html","Videomúsica sección videos, Rico","Videomúsica, información y videos. Rico"),new f("//videos.videomusica.es/roberto-carlos.html","Videomúsica sección videos, Roberto Carlos","Videomúsica, información y videos. Roberto Carlos"),new f("//videos.videomusica.es/roxy-music.html","Videomúsica sección videos, Roxy Music","Videomúsica, información y videos. Roxy Music"),new f("//videos.videomusica.es/roy-orbison.html","Videomúsica sección videos, Roy Orbison","Videomúsica, información y videos. Roy Orbison"),new f("//videos.videomusica.es/Sade.html","Videomúsica sección videos, Sade","Videomúsica, información y videos. Sade"),new f("//videos.videomusica.es/sam-cooke.html","Videomúsica sección videos, Sam Cooke","Videomúsica, información y videos. Sam Cooke"),
new f("//videos.videomusica.es/Shakira.html","Videomúsica sección videos, Shakira","Videomúsica, información y videos. Shakira"),new f("//videos.videomusica.es/simply-red.html","Videomúsica sección videos, Simply Red","Videomúsica, información y videos. Simply Red"),new f("//videos.videomusica.es/spandau-ballet.html","Videomúsica sección videos, Spandau Ballet","Videomúsica, información y videos. Spandau Ballet"),new f("//videos.videomusica.es/stevie-wonder.html","Videomúsica sección videos, Stevie Wonder","Videomúsica, información y videos. Stevie Wonder"),new f("//videos.videomusica.es/Sting.html","Videomúsica sección videos, Sting","Videomúsica, información y videos. Sting"),new f("//videos.videomusica.es/Supertramp.html","Videomúsica sección videos, Supertramp","Videomúsica, información y videos. Supertramp"),new f("//videos.videomusica.es/Tequila.html","Videomúsica sección videos, Tequila","Videomúsica, información y videos. Tequila"),new f("//videos.videomusica.es/terence-trent.html","Videomúsica sección videos, Terence Trent D'Arby","Videomúsica, información y videos. Sananda Maitreya-Terence Trent D'Arby"),new f("//videos.videomusica.es/thalia.html","Videomúsica sección videos, Thalía","Videomúsica, información y videos. Thalía"),new f("//videos.videomusica.es/the-carpenters.html","Videomúsica sección videos, The Carpenters","Videomúsica, información y videos. The Carpenters"),
new f("//videos.videomusica.es/the-doobie-brothers.html","Videomúsica sección videos, The Doobie Brothers","Videomúsica, información y videos. The Doobie Brothers"),new f("//videos.videomusica.es/the-jacksons.html","Videomúsica sección videos, The Jacksons","Videomúsica, información y videos. The Jacksons"),new f("//videos.videomusica.es/the-manhattan-transfer.html","Videomúsica sección videos, The Manhattan Transfer","Videomúsica, información y videos. The Manhattan Transfer"),new f("//videos.videomusica.es/tino-casal.html","Videomúsica sección videos, Tino Casal","Videomúsica, información y videos. Tino Casal"),new f("//videos.videomusica.es/Triana.html","Videomúsica sección videos, Triana","Videomúsica, información y videos. Triana"),new f("//videos.videomusica.es/U2.html","Videomúsica sección videos, U2","Videomúsica, información y videos. U2"),new f("//videos.videomusica.es/umberto-tozzi.html","Videomúsica, Umberto Tozzi","Videomúsica, información y videos. Umberto Tozzi"),new f("//videos.videomusica.es/van-morrison.html","Videomúsica sección videos, Van Morrison","Videomúsica, información y videos. Van Morrison"),new f("//videos.videomusica.es/victor-manuel.html","Videomúsica sección videos, Victor Manuel","Videomúsica, información y videos. Victor Manuel"),new f("//videos.videomusica.es/Zucchero.html","Videomúsica sección videos, Zucchero","Videomúsica, información y videos. Zucchero"));
var L=1, D=1, M=1, Ws=new Array (
"10~la:","100 fVD","12#=,(","13 a","14&aVL)","15P","150 n","16#kJ","175 4","18 a",
"19H","190&","1927$#","1941$#","1943 k","1951 w","1965 d=","1967 d","1968^L","1969_",
"1970}i","1971 6","1972#","1973 b_0&","1975 g","1976T","1977Q","1978}","1979'ug","1980'+&",
"1981 yfI","1982^I<","1983^","1984U(","1985#","1987DB","1988 7","1990Z","1991 l;","1992G",
"1993(","1994`","1995 s;","1996OE","1998]BA*","1999(","20 8C","200 7/","2000 a^","2002 1*",
"2003(M/&","2006T","2007O","2008)","2009P,","2010 s^","2011 l","2012/","2014#_","2016*)('&%$#~}|{zyxwvutsrqponmlkjigfedcba`_^]\\[ZYXWVTSRQPONMLKIHGFECBA@?>=<;9876543210/.-,+*)('&%#hUD:",
"2017 1(","2018 sJ$","2019`B4","2020U","2021J$","2024*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%#","21 h=","22&","24 9)","25]D",
"26 gd","2600L","28O","2hhzmrmahxuJ","30 21","300 kg","35G%","360)","365 9","3x1(",
"40_SK=","4dwcpqjcw3yJ","4eJ","50(k@?=)","500H","5000L","52 4","53 s","55=","60~vk^[URLEC:",
"70)%|yg_[QGEC?;653/'B>.'","80&~zyxwtqljhfec_]XVQN?/.'-","90 yqmlhe]\\70X","92 2","99)","álbum*'&}zj[ZUPB;76,&#lg^/a9","álbumes%xia^][OMJ?;","álgido e","ángeles[","ánimo e",
"â¡qué x","árabe s","árabesX","ásperaJH'","â¡tan q","â¡utópico h","ávida^","â¿ h","â¿es 1","â¿o/",
"â¿podrás 1","â¿quiénH","í“pera`","â€œwhatâ€™s[","â©*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","él%zk[LHB<:","época'd[Q5('r","éste&","éxito&#~}|ywplga`_]YXWOLID;987643.-+)){f^B's&","éxitos yslk`[UTJ@>310)(%~E",
"â®*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","Échame)","Él*^UI=","Éxitos t","ílvaroO","íngeles.","ópera 4","órganoR","añadieron u","añadir#",
"año'#yunlia`_UME=1/+*)sOIB;&^","años)(${ywvtsrjdb\\[YXWVTSNMGCB@?;:865421.&%'&zoma`_^PJ>93)'k=~","aún z","aaron$#","abandonóUO:4","abandonaron f","abarcando&","abarcar#","abarrotados f","abba%",
"abbey$","abc~","abejaK","abierta q","abiertoX","abiertosX","aboutTM","abría[","abrazarte)","abre%",
"abrió fXA3","abriendoN","abril hUH","absoluto[&","absorbe 8","absorbente f","abuelo)","ac&","acabó%,","acabando$",
"acabar{w","acabaron|","acaboA","acústicos{jM","acaparado*","acaricia n.","acariciaban;","accidental h","accidente%$bLd","according z",
"aceite(","aceptar q","acercándose 9","acercaban^","acercamiento?","aceroM","acertada(","acidFG","acogedores 8","acompañadaE",
"acompañadas 60","acompañado h^KHD","acompañados?","acompañamiento q","acompañando t","acompañar-","acontecía[","acordes_","acreedor(","actúa q",
"actitud.","activa z","activarP","actividadH","activista a","activo vrib^U*","actriz s\\+{","actuaciones>-&$","actual v/","actuales 9",
"actualidad s-","actualmente y","actuandoL","actuar#N","acudir%","acuerdo{C","acumularG","acurrucarse>","adam&","adams c",
"adaptándolo 9","adaptablesO","adaptación^]+","adaptaciones]","adaptarse:","adecuada a","adecuadoD","adelantado$","adelantarse:","adelante`",
"adelanto~","además(sr_","aderezado*","adiós^I","adicciones[","adictivas%}","adjetivos v","admiración b[","admiradores&N","adolescencia.",
"adolescenteM","adoptó l","adoradores%","adoroS","adquieran&","adquirióT","adquiriendoP","adu q","afamadoT","affair\\",
"affirmationC","afloran t","africa s","africana$#","after%>","again x5","agapimú+","aglutinar[>/%","agnetha%","agradable 3",
"agradables q","agradecer(","agrandar k","agresivaD","agria r","aguasY","aguirre*","agujero 8","agustitoN","ahíL8%",
"ahoraY/","ain[","air)","aire]","airearon m","aires 8/","al('%#rqmiga[ZXWRQPLKJEDA?=9870/,%&zxtc^]ONIHGB;6'}o_YU>1(&)e-","albaU","albert)","alberti+",
"alcalá+","alcance(","alcanza`^","alcanzó[B?^","alcanzable t","alcanzado&Z","alcanzanZ","alcanzando w`\\LJE","alcanzar r?4.","alcanzaron'#~|/]",
"alcohol\\H","alegatoU","alegra s","alegría^","alegria^","alejandro sY","alejo yW","aleluyaU","alemánL3","alemania^]",
"algún\\","algo re^;$#4z","alguien:","alguna ng_9'","algunas%J-%","algunos(a`\\[L<:4","aliñoD","aliento r","alive?/","all*)('&%$#~}|{zyxwvutsrqonmlkjihgfedcba`_^]\\YXWVUTSRPONMKJIHGFEDBA@?>=<;:98654310/.-,+*)'$#[ZC&%pQL72(",
"allí z.","allá)kYs","alma*(}treda_UTSIF=86+'q$#","almas d`","alone w'","alrededor q;","alright~}","alta b","altas aX?4,","alternativo l",
"alto#~}up]ZD<&","altosE","always(Ff","am 51","amaL","américa kb","amados w","amaiaO","amamamos x","amante?4",
"amaral*","amarillas b","amarillo s","amaya_","amazingD","ambición[","ambiciosa h","ambiental[","ambienteN?","ambigí¼edad'",
"ambigua&","ambiguo:","ambos fa","america x","americanL","americana}L$#","americanasP","americans:","amigo<","amigos^n",
"amo'","amor{n_URKI=9.'%`+)aV4","amore{","amores a","amour#","amplio}J&","ana)^]+","anatomíaP","and(&~|ztplhgEB?;70-'&y^","andadura%]OD",
"andalucía^","andaluz%X","andaluza%","andrés y","andrew$qD","angel o","angels z","anglo q7","anglosajón'YLI)","angus&",
"anillo}","animadaT","anita\\","aniversario%","annabel j","anorexia|","another igT","ansiedad)","antaño 5","ante&$td[6.+&U",
"anteriormente>","antes%url[UJA","anthonyY","antiguo g","antojaba$%","antonio mHN,","anunció^","anuncian%","anunciarD","anunciaron;",
"anuncios{","última&r","últimas fZ","último r^;9,","últimos sU","única b`[Z$#&","único vskSMH@;:4'","únicos>","ap 1","apacibles|",
"apadrinando.","aparatosaH","aparecieron~","aparentemente`","aparición~TPC3","apariencia hP","aparte(","apellido~","apenas~{[=)","apetitosos y",
"apl 1","apodado e","apodera he","apodo.","apogeo uN/","aportaciónH8","apostandoW","apoteósica^","apoteósicas;","apoyadoF",
"apoyar[","aprendíS","aprenderX","aprendiS","aprendió a","aptas h","apuestaO8","aquí#YU","aquel'#{z_\\<9kd","aquella'd",
"aquellos r^9","aquiU","aquiles s","arby 9z","arco}","ardióX","ardiente t","are iQJE.v","areethaP)","arena(",
"aretha q\\65","argentino y^","argumental[","ariadna{","arie$#","ariel y","arma\\","armadura,","armario%","armas~",
"armonía}_Z8","armoníasN%","armonizadaM","arms d;","aromas$","aroundC","arquitectura f","arrancó^","arrancaron j","arrasando{",
"arrastrándote 5","arrebatándonos,","arrebatóT","arrebatadorW","arrebatadora t","arrebatadores 8","arrebato&","arreglada^","arreglista a.","arreglos|_?",
"arriba)","arrollador&","arrows)","artículos f","artística$","artísticamente wk","artísticas)X","artístico j~{","arte#U","artes(",
"artist h","artista~ta]ZLD'zs`4","artistas*)('&%$#~}|zyxwutsrqponmlkjihgfdcba`_^]ZYXWVUTSRQONMKIHGEDCBA@?>=<;:8765210.-,+*('&%$#{e\\PJF943/vL)[","artsM","as l\\","así y`XSHGFD=;.(~4","ascapL","ascendenciaU","ascendióL","asesinado ur",
"asi*o","ÚltimoX","asomaM","aspecto,","aspirando#","aspirar]","asturiano)","asumiendo[","at 2(","aterciopelada dT.",
"aterciopelado r","atlántico=","atlanticP","atmósferaM","atrás%[T/","atractiva q","atractivo qF","atrapado$#","atrapan}","atrapar q",
"atraparte te","atravesando)","atraviesa rM","atraviesan e","atrayente q","atrayentes 8","atrevido*","atronadora'","audiencia rn^","audiencias#",
"augusto w","aumentarC","aun`","aunan#","aunque tlke]UM-%","aupó]","auparon,","aura e","aureola q","auseron j",
"auspicio~","australia&","auténtica rR(","auténtico^KH","auténticos y","auteU","autenticidadY","autobús^","autodidactaX","automedicarse$",
"autorQ","autora s6","autores)L","avalan a=","avalon o","avatares%","avec]","aventura m","avioneta d","awardL",
"awards n`^L;","away;$#","ayer,","ayudaE","ayudándoles?","ayudó&","ayudaba~","azaharaXR","aznavourL","azulXn",
"bálsamo(","bésame mS","babaji x","babe.","baby#5","babylon 3","bachataK","bache~","back#~&","baduP",
"bagajeV","bahia d","baila*","bailarK","bailarina s","baile~wfa1","bailes 3","bailey>","bajónD","bajista wumi",
"bajo&%~zji`^71/.-$","baker\\3","balada*Y","baladas pDB>=5^","balance+","balancea)","balanceándose}","balazos[","ballet{u","baluarte*",
"bandV","banda~ulji;1-&%&G?/}xa","bandas lPB>9;","barón-","barbra 7/","barcelona=","baron-","barranquilla s","barreras s","barrett g",
"barricades u","barrio\\","barroX","barroco$","barry$/.","basada-","bastantes-","batalla:","batería&%ui[>-","baterias?",
"baterista i","battM","bay d","bayou p","bazasW","bbc e;","be iZPJE/&~|\\@9","beach p","beast 7","beat 7",
"beatles pd%","beautiful p<","beauty 7","bebían 9","beberC","bebiendoN","because 7","becker<","bee/","been 6d",
"beethoven^","beforeL","beginL","beguineL","begun|","being'","belén)^+","belfast(","believes}","bella pM7+",
"bellas)|_W,","bellezaXUH,","bellos}|+","belongT","benéficas^","bendecirnos.","bendiciónK","benditaK","benegasO","bengalí$",
"benidorm kL=","benny%","bensonC","beret h","bernie@","berry[","besarte y","beseY","beso b","besosV",
"best 5E","bestia 7","bibliotecaQ","bicicleta s","bicyclesM","bien&H$#)/","bienvenidos^","bigVB","bikinaV","bilbaínoA",
"bilirrubinaK","billboard rnLB","billie q","billy+0$","bipolaridad x","bird$#","birdland#","bit x","bites i","bizarrap s",
"biznietoN","bjorn%","bkajs8wayd4$","black}1&","blame~","blanca r2","blancas d","blanco}r_:+(","blancos tp","blige\\",
"blue(}t/pe","blues*([WTM>;^B@","blueyF","bob p","bobby 32","bocaA9","body~","bohemian i","boleroVS","boleros=",
"bombazo?","bon&","boney 3","bonita a","bonitas u","bono&","boogie~>","boom#","botánico j","botas-",
"bote d","bottom*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","boulevardH","boutF","bowie:","boy#J$","boys pf","boyzZ","brand w","brandy=",
"branigan'","brasil#","brasileña n","brasileñas+","bravo b","brazilian n","brazos)","break i","breakfast x","breaking@",
"breakthru i","breathe)","breezinC","brian i&&o","brick g","brillante%{ztM","brillantesH","brillantez c","brillos\\","bring wr?",
"brit(M;","británica xG","británico(t@/)","británicos gf:","broadwayC5","broche&","broken'","bronx\\","brooking m","brota&c",
"brother[","brothers;}$#","brown(F3","brusca$","brutal'","bryan o","bryson 7","bucaneroH","buckinghamB","buddahE",
"buen&#{xwi^VRJIF90PE","buena s^[GFC31","buenasR","buenos^?","bumerang^","burbujasK","burlóU","bursátiles{","buscar*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","buzzG",
"by*)('&%$#~|{zyxwvusrqponmlkjihgfedcba`_^]\\ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:986543210/.-,+*)('&%$#}[t7","bzrp s","cálida z","cálido 86","cálidos qO","cáncerT:98,","cárcel.","céline 7","cénit^","cómeme 8",
"cómo ri_.*","caídaH","caído j","cabeza'","cabida;","cables z","cabralesA","cada%H21","cadenas q","caducidad e",
"cae%","caer&","caféK","calabria-","calamaro y","calaronU","calderón_","caldwell 2","calidad('#{qbZRFB(%","calidez+",
"caliente}{","calificativo`.","california p)","californiana}","call@","callaoK","called v5","callejón[","calor j","cama n",
"camaleón:","cambióD","cambiando~_","cambiar.","cambio rC.","camilo 4","caminaré'","camino%[X;8","campoJ","camposX",
"campuzano-","can~.'$#","canaan 6","canada 7","canadá a","canadiense a","canalizando{","canción)&nkg^RL=7-r_UTQEd+","cancion s","canciones)&zyvurqmlgfdb_^]ZXWVSRPNMLKJGD><:875210.-+('%'%}xwpke@?;4|[,HU",
"candiP5","candidez p","candoroso 6","cano+]","canta)(","cantadasI","cantan 4","cantandoT","cantante${vYWPLD@>=620'&rI","cantantesE7('",
"cantar~tkdLJ","cantará_","cantautorU","cantautora 6","cantautores 0+","cantidad 4","canto a","canzetta 5","capaces%tIF>","capacidad&I",
"capasX?","capaz({web[YXKD74,'z","capitalU","caprichos b","capturaban 6","capturada d","cara n","caracter]","característico&","caracterizado%",
"caracterizarK","caras d","carbónX","carcomido g","cardíacoD","carelessD","careyZ","carga&","cargada aH","cargadosE",
"cargar 1","cargarse^","cariño n^","caricia*","cariciasM","carisma jba","carlos sWnm_","carmonaN","carne k","carole 6",
"carolinaW-","carpenters|","carrack e","carrera~}nedaVTJ@?=<;81.+)^","carreteraL","carry 2","carta=","cartas b","casa smhdA","casal$",
"casi ztpd_RPNL741+'$","caso/+'","castellano%","castizoH","castro-","católica l","catalanaU","catalizarF","catalogadaJ","catalogados#",
"catalogar z","catapultó ul&","catapultarlo k","catapultaron b","categoría b","causa(^","causas^","cautivarC","cay74$","cayendo[",
"cbs~-","cds%","ceilingQ","celeste*","celine/","celtic(","censuraU","centrándonos$","centró y","centro e1",
"century x","cercana:","cercanosO","cerebralUH","cerebro ge","cerrar{","certificación a","certificaciones\\","certificadosL","chacon 9",
"chains c","chaka\\","chambao 8","champú$","champions i","change r","changes:","chanson#","charles qL9","chelsea f",
"chica,","chicas a","chico&","child xD","chileL","chilenas w","chill 8","china}:","chinaâ´sL","chocolate 9",
"chris f","christmasZ","ciega s","ciego vI","cieloY","ciertoG","cima 8&","cimientos-","cinco|","cineU",
"circle c@","circula}1","circulaba r","citados>","city#[","ciudad^H.+","ciudades)","civiles r","clásicas#^","clásico}JE?9.",
"clásicos y9","clímax[","clanW","clapton e","clara z","claramente 8","claridad'","claro#","clases{","clasificóE",
"claudicaran d","clayton&","climax?","close|","clubs#","coQ","coche$b","coincidieran r","cojoH","colabora a",
"colaboraciónH9","colaboraciones*^","colaboradora-","colaborar e","cole]","colectiva i&","coletazosU","coletilla\\","colombia s","colombiana s",
"color*}tre2","coloridoF","colour 7","columbiaE","comaU","común 1","combinaba[","combinaciones o","combinando a","come#r",
"comentaP","comentábamos_","comentan 5","comenzó kD","comenzando#","comenzaron]O","comercial}XPB","comerciales tf","comercialidad xD%(","comerse z",
"comesC","comfortably g","comienzo'&d_[J1$R","comienzos(|qp^W-][","commodoresQ","como'&xrnmjib]\\XVQNKICA@610/)*~|uskhfcYRLJFD<:2,'%)%#}{ted_^UPB?>;54.+($zwpla`[HE=9q(","compás q","compañía r-+","compañías.","compañeraH,",
"compañeras a","compañero mH","compactaba|","compactadas 9","compaginaban x","compaginado;","compaginando<","comparadaP","compares h","compartió^T",
"compartir fX","comparto:","complemento-","completa a","completas 7","completo 4","complicado\\","complicidad>","componían i","componente_D",
"componentes#if1_","componer<,","componiendo u","composición rZTRD","composiciones*qYOI6/,+%HB)","compositiva)JF,","compositivo_","compositor$vueWML@;420.*)'>","compositora{aP6*","compositores('_L6",
"compostura+","compromiso 6","compuesta}t+","compuestoN3)","compusiese)","compuso 6","comunes l","con tnjihfSRBA6$#*|wqomgbWPOM:50'&{xp`ZJIC<981/&%(#}v]VTQLED@>=74.+*%yec\\YNKF-,zldUH?;)('$rkXa_[s^","concibió`","conciertoH(",
"conciertos gNL;","concreto l","concursoP","condenadosU","conduce_","conducirJ","conductor'","conduzca e","conectandoX","conectar ws",
"confesar z","confianzaP","conjugando%","conjugar z","conmigoC","conmueve 5","conocíamos z","conocemos a","conocer hf^OC","conocerse 9",
"conocida&{jE?5s","conocidas g[(","conocido*(#wh\\L=:","conocidos'nfOG>/%","conocieron f","conociese h","conquista.","conquistarte=","consagrándoseA","consagró`",
"consagrado,","consagrar f","consagraron x","consagrarse~","consciente q","consecuencia$shD9,","consecutivas]","conseguía(","conseguido`(","conseguir rkeY",
"conseguirlo`1","conservan q","conservando q","conservatorio=","consideraban_","considerada{q","considerado&rYT0","consideradosN&","considerara f","consigueU",
"consiguen{rt","consiguió'r\\'","consiguiendo z","consiguieron>/*","consiste#","consolidación$","consorcio_","constanteL","construimos a","consumado d",
"contó o","contaba 94","contabanE","contactoC","contadoH","contador 0","contagiaF","contagiarnosW","contagiarse@","contagiarte'",
"contagioso~","contagiososD3","contaron[J","contarte%","contemplar d","contenía d[","contenida%?","contenido g","contenidos*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","content*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#",
"contigoOHS","continúa)(k+","continúe_","continentesL","continuó^<;9","continuado pi^","continuando y","continuar aO,","continuaron lE","continuidad[",
"continuoE","contra wE:]U","contradecirJ","contradicciones l[","contrapartida l","contraria$","contrarioKJ","contrastada+","contrastes 8","contratiempos,",
"control[K7~","convencional$","convencionales?","converger 9","convertiéndose 9","convertidaK","convertido oL:)","convertirse rf\\QNE","convierteO","convierten b",
"conviertieronP","convirtiéndolos 3","convirtiéndose&sqa_A","convirtió zd`N[","convirtiera/","convirtieranD","convirtieronZ>","convulsa[","cooke z[r","cookieconsent*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#",
"cool 3","copa s","copia 9","copias l^E/*","corazón)(na_[UTSI.)^=","corazon)jS","corporal,","corre$#","correctaP","corriendo*",
"cortes-","corto vY>","cosa%","cosas(k","cosechados>","cosechando=","cosechar sa","cosi*","cosmicG","cotidianasH",
"cotidianidadX","country(~pQB5)$#}","cowboyG","coz-","crítica[","crítico f","crazyLg","creaban?","creaciónA?","creada u",
"creado 3%","creadorU","creadores r","cream h","creando@?","crear(2","creatibidad 6","creativa-,","creativas a","creatividad$Q",
"creativo v@:~","creativosC","crece+","creció)","criada\\","criado.","crime x","crisis zx","cristalina|M","cristalinas c",
"cristiano s[","cristinaU","criticado(","cropper d","cruce z","crucesI","cruda r","crudezaH","cruz]","cruzar)",
"crying p","cuéntameO#","cuídateO","cual'r6","cuales g","cualidad t","cualidades`RC2","cualquier*tsf]ZQC?><1&","cualquiera*{]VH","cuando&%zpe`XTE?=;85/[J",
"cuantosM","cuarteto#l","cuatro m;","cubanos j","cueca w","cuenta')'","cuenteA","cuerdas sr\\7","cuerpoU","cuesta]",
"cuidadasQOA*","culpa w)","culto&lN","cultura a","cumpleaños[","cumplir$","cuotas/","cupid r","curando a","curiosamente h",
"currante k","curtidaH","curvasH","cut u","cuya{e[","cuyo~4","da(","dándonos b","débil 1,","década)(~uslhge\\[VNC<765.'B3",
"décadas)(tpf^ZHFC+&(","décima,","déjame_8","día)({ka8","días^*","daba m^Z","daddy\\3","dado*d","dímeloY","danP81<",
"dance wGD53zf:","dancing fQ/%","dandoQPFC8q","daniel&","danza w","danzan w","dúo|9","dúos|f","dar*~zyedXJ","daría~",
"dark*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","darlesD","darseO","dave&","david:","davies x","davis*","day wZ6","days|z","dc&",
"de$#xuoKYW8ZR:*yvpi`SOA2lcG<)JI30mjVTQDB@6|wtqF5-*()#}hb\\>'nM=']P9%sgfeN71dX{C;.4&k+%_E?~zraUH(&L/$^,[","deacon i","deadT","debajoVP","deberíaC","debido d_","debilidad[","debilitóQ","debilitamiento[","debut zmZPJ<9",
"debutó=5","decíamos lJ","decayendo~l","decide~","deciden a-","decidió[","decir x]XI>7_","declaración j","declive[/","dedicabanR",
"dedicada g^I","dedo}","dedos;","dee@","deep/","define$#","definen(","definiciónK","definir voY","definitivaD$",
"definitivamente/","definitivo^*","degradamiento[","deja#saYF","dejándonosU","dejó)qhd9(","dejabaN,","dejaban 3/","dejadoH5,","dejando.",
"dejar zH,$","dejaron mRO3","dejarse qaGC","del$}xwomkaYRGFA@3)$#*)'|{uqpjfcb`ZPOMLKJID?5420~zvtige\\XWVSQ><7/-,&%#snlhd]UNHE=:961.*('%^[;8+&y_CBTr(","deleitándonos)","deleitado(","delicadaM$#","delicadas|","delicadeza@;6","delicado r>",
"delicia e(","delicias x<","deliciosos#","demás_\\T*","demonios[","demostróJ","demuestra 7","denman q","denomina 8","denominado(",
"denominador 1","denominan l","dentroYMB%","depositar b","depresión,","depresiones\\","depresivasD","depresivosH","deprisa$","derecho a",
"derechos r","derrameH","desátame`","desafiandoH","desafiante-","desapareció|","desaparecido_3","desaparecidos w","desapareciendo 9","desaparición,",
"desapariciones/","desarrolloH","desaveniencias%","desbocadoJ","desbordanH","desbordante h","desbordantes&","descalzos s","descarada&","descaro yPm",
"descartar n","descendióB","descomunal i","desconfiarN","descorchar\\","describiendo w","describir,","descubrióM","descubrimiento cP","descubrir vt",
"descubrirlos m","descuidada,","desde(&}ytslgda`^SRB?+*%{_YG:)","desembocan 8","desempolvando%","desencadenante 9","desenfrenada}","desenvuelvía(","deseo$","deserve f",
"desesperada%","desgarrada dT","desgarrador 7","desgarradora rd","desigual;","deslizándose t","deslocado~","deslumbrante%","desmedida 4","desnuda%M",
"desnudando r","desnudesU","desparpajo~","despegue^","despeinarse 7","despiertaW","después%~r_^ED9a","despuntó k","despuntaba~","destacadosA",
"destacando n","destino]L.","desván)","desvaneciera|","desvanecimiento/","detalles n","deteriorar,","deterioro[-","detonante 9","detrás%",
"detroit[","devaneos(","devices f","devoción fG","di'","dia(j_[RC+","dió}zfd_","diamante*","diamond g","diamonds h",
"dianaQL","diariosP","dias&lH:","diceH","dicesS","dicho({","diciembreD","dictadura w","didn 0","dieG",
"diegoH","dieronRN;","diezA","difícil&","difíciles&","diferencias)","diferentes_3(","dificil qnMC(%","dificiles,","dificultadX",
"difruta>","digan k","digginJ","digna(","dignasM","digo)","dijeH","dime y'","dimensión&","dimmi'",
"din{","dinamismo>","dinero[","dion/7","dionneE/","dios+","diosesN","diríaP","dire;","dirección$P",
"directamente ea","directo rWC>(^;","director$U.","directos>*","dirigió{","dirigida^","disco~zumkJIFB>32.*d<9?/","discográficaVJ)~","discográficasE","discográfico z3P",
"discografía v%","discos&rnmgfd\\VIGDA=<;64-)(&zk]?7L","discoteca f?<","discovery?","discurrido:","discusiones[","disfrutaban d","disfrutado'","disfrutando zy%","disfrutar(#zm_F85",
"disfrutarlo(","disfruto 2","dislumbraba z","disminuidos)","disolución mlXO;%","disolvió a","dispares^]I$","disparo r","dispuestas q","dispuestoX=",
"disqueraI","disqueras{","distancia n","distanciándoseE","distina-","distinguidasT","diva+`","divagando'","diversas^","diversión>",
"diversidad/#","diverso#","diversos^PA(","dividida g","divina`@","divino*","do 29","doble^)","dock d","doctor^",
"doctorados(","does 7","dollyL/","dolor&","domina=","domingoL","dominicanoK","domino f","don xiePFtsB@?2$#1","donâ€™t c",
"donald<","donde)(&{zxsrlhgdb`_^[ZPA:98.-)UH(#=","done f'","donna*","donostiarrasO","doobie}","dorada|('","dormirW","dos)j_[YIEA)aU","dosis b,",
"dotándolo(","dotó?","dotadasE","dotadoTD","dotesX2.","down c\\@~?","drG","dreamF","dreamer x","dreamloverZ",
"dreams 0pB","drogas|g\\HD[","drove p","dublinesaP","duda qke_UB&b","dudoS","dueño[T","dueños*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@>=<;:987654210/.-,+*)('&%$#?3","duela k","duendeI8",
"duermanX","duero=","dueto c","duetos[","duke v","dulce dO75","dulces.","dulzuraJM","duophonic 9","duperJ",
"duque:","dura:","duración g","durante}UB$","duro,&","dust i","dyango=","dylan p","earth>","easyQ9",
"ecologíaX","económica[","edén$","edad)kVM","eddie 9","edema$","edge&","editadoI","eduardo%U","educación gc",
"ee{","efímero 9","efecto%","egocéntrico h","egocentrismo z","ehulq$","ejecuciónU","ejemplo{","ejerce s","el'xupmgfcbQF<7)|yse]VKIGE850,*wlW61({qYTDC3.+($#}jd`ZPJA=42*)%ihSM?;%&nXON>:9zrk\\B-'&~a_UH/L[^",
"elaboradas]D","elcetrónica{","electrónica:","electrónico>8","electrónicos jG8f","electric?","electroG","elegancia%oVTFCq","elegante}[EB'","elegantes|",
"elegidas@","elemento-","elenco>","elevarles%","elevaron;","elixir,","ella usrqPME65a{","ellas'UH:w<","ello(#{qliHG?42","ellos&~|tpmljf_SONMI>0)}yi&%",
"elocuente*","eloise$","elton eE)@","elvis p","embajadora s","embarcado j","embargoH","embelesar'","emblemáticas 1","emblemático&",
"embrujada$","emergentesP","emi 9","emigróM","emisoras 9","emoción)WB$#","emocionándonos d","emocional[","emocionar w","emocionarmeU",
"emocionarnosK","emocionarse^","emocionarteX","emociones)(eYI,+","emotividad zQE@","empapeM","empaticen e","empedernido=","emperatrizE","empezó p[VT",
"empezar[","empezaron p","empiecen<","empiezaX","empiezanU","empiezo`","empleandoH","empresaria{","empresariales)","empuje{",
"en xnmYRJ*|hedXGF:81'utqolgVKI@;652'%}jicSQ?=0.%$#*&ywbTNC>9,+zpZUM7))~aPEDA3/((vk]\\O4rf<-Bs`_&$L#{[H^","enérgica 6","enérgicas}","enérgico['","enamoraY","enamoró k","enamorado*j=","enamorarY","encandilaY","encandilar{",
"encanto'qdPGF(","encantosD","encargó d","encarrilando{","encauzadoR","encerraba h","encerradoS","encienda<","encogerU","encontraba_",
"encontraban z","encontramos_","encontrar#G(","encontrarnosD","encontrarse.&","encuentre(","encuentres s","encuentroS","end lfT","endlessQ",
"energética&","energía}yda^41&F>G","energías{","enero:","enfermo`","enfocando{","enganchados 0","enganchar t","engancharteI9","englishman w",
"engranajeO","enmascarandoU","eno o&","enorme nTQ4","enough[.","enriqueció 1","ensamblándolasH","ensayarR","enseñándonos~","enseguidaJ",
"entender`","enternecernosK","enterradas z","enterrados z","entonaciones k","entonces'#{z_\\9","entró=","entrada_O5","entramado+","entrando a6&",
"entrar?","entre&}{aYE%A)'r","entrecruzaban`","entusiasta^","envidiableVQ","envidiables&Z","envoltorio z","envolturasM","envolvente}","envolverá*(",
"envolverte e","envolviéndote+","envolviendoM","eqp1s$","equivocada{","equivocaríaA","era$~gc[XTQNDC<5/-zf","eran f^UNB>%","eres_","eric e",
"erizarmeU","erranteR","erupción t","erykahP","es&%$#|yxwuponmlkjifb`[ZWTRQPONLJGEDA?;9863-,+%(zec^]\\VSKIB@>=<:75210/.*)&)'~}{trdYMFC$#sg4('*vqaXh_UH","esa'&|t_PKD<763-'","esas pl\\[U@e","escándalo k","escándalosD","escénicoU",
"escalofriante}","escapan+","escape 5","escenaF&","escenario qpia[H'","escenarios{^","escenasI","esclavitud[","escocés;","escoceses&",
"escondeP","escondite`","escritor 9","escucha s","escuchaba d","escuchadas|M","escuchado_","escuchamos/","escuchando qX1","escucharGF/&$#",
"escucharle e","escuche{w1","escucho 2","escuela(j","escultura$","ese'xtsqnhRIC/,$#~e_P9","esencia%gM>,","esferas 4","esfuerzosL","esguince$",
"eso mWP(","esos}ztmfdb_][P?9,>-","españa#j`U4-+A^","español)'yvt^UNLI8-)`]4,*","española$`_","españoles)_","espacial^","espacioOMH*","espadaA","espaldarazo*",
"espaldas aOC","esparce,","esparciendoH","espíritu]>","especial(ztsje`_VSI?&$#","especialesS","espectáculo^","espectáculos 3","espectacular('h>.'","espectaculares g\\G",
"espectacularidad>","espectante z","espectro'&","esperados`","esperando%","esperanzado r","esperanzasE","esperar`WB","espinita)","espiritual,",
"espiritualidad('","espléndido v","espontaneidad l","esporádicas^","esposas w","esse n","est$#","esta&xwqldca`_\\PJGB=5{","está_820n","estás_8",
"estéX","estí¬loQ","estaba}lg\\PE-","estaban>","estaciones,","estado e","estados#ka_^","estadounidense la90","estamos|IN","estando~zN",
"estar fU0","estaré z","estaréisC","estas f2","estatua j","estatus x;,%","este*(#zrld`QNJHCB541)$#}s(","estilo$#kYXRPNJEB1}","estilos*aIA/(","esto sa_^",
"estos%","estoy vOH","estrafalario@","estrella{kTQE*","estrellasZ","estrellato[P","estremece 5","estremecedorasU","estremecedoresD","estremecerte(",
"estribillos l","estricta'","estrictas g","estructuraX","estudiaba fM","estudiando a","estudiar a","estudio,","estudios$","estupendasR",
"estuvo#b[;","etílica&","etapa&%|QHDA<:-w_,","etapasD","eterna x","eternamente,","eterno 4","eu n","europa#k`_3","europe l",
"europeos*","eurovisión k_L7%","eva*","evans&","even x","ever w5(E","everybody l$#","everything.","everywhereB","evidente a9",
"evidentemente z","evitarD","evocandoG","evolución]C","evolucionóB","evolucionando ug","evolucionarZ","ex m","exageración_","excéntrico[",
"excelencia^,","excelente<","excentricités`","excepción_","excepcional 6+","excepcionales>","exceptuando]","excesosH","excitación?&","exhalan'",
"existíanB","existencia@","existencial z","exitosaD","exitosas i","exitosos 7","experimental zg:","experimentales o","experimentarX","expertos l",
"explain(","explicaciones z","explorarX","explosión/'","explosionar>","explosiva&","explosivo y","explotaZ","explotado)","explotando{>",
"exponentes e","expresa d","expresaban l","expresar b","expresso;","exprimir f","exquisita q@?","exquisitasN","exquisito e","extensaU",
"extenso(n","exterior t","extraido 7","extraidosF","extraordinaria b3.","extraordinario|:","extravagante ih:&","extrayendo*","eye l","eyed}te(1",
"eyes oC2e","fácilP@q","férreo~","fértiles h","fórmula f","fórmulas f","faceta)\\JD,)${","facetas)","facilidadU:","factura$",
"fagen<","faith wD","fake t","fallecimiento d&","fallido]","falling 7","falloD","falsete}p>","falsetes>","falsetto/",
"faltado 8","famaTE?;630'&(","fame&EB:)","familia~_N","family\\","famosa gd(","famoso]7%","famosos$S+","fans%","fantástica}t4",
"fantásticas*","fantasy>","far;","farian 3","farrell 3","fascinantes>","física$#","físicamente h","físico,","físicos)",
"fastD","fastuoso>","fatal m","fatherD","favorX","fears c","febrero(","fecha e","feel l~6","feelin~",
"feeling cC1","felicianoI","felizI","fell zJ","femenina sc`Z6","femeninasZ7%","femme]","fenómeno k","fentanilo h","fergie 1",
"fernando m","ferry o","festival 7%L=","festivales k-","fever/","fibraH","ficharI","fiel n^XM","fields w","fieles#",
"fiesta]","fiestasO","fifa s","figueras`","figurar)","figuras<","figureD","fijóJ","fijarse&","filaX",
"filántropa sa","filadelfia.","filipinasU","filosófico g","fin(|{^,+R","fina%","final$|yd[/","finales('yc[XR;/","finalizándola]","finalizó^",
"finalización%","finalizadaB","finalizando w","findT","fine l6","finura q","fireI0>","firmaZ","firmado$","firmar$",
"firme\\-","firstE.","fitipaldisA","fitoA","five~","flackP","flagelantes i","flame 2","flamenca%","flamenco%8N",
"flamencosXN8","flauta a","fleetwoodB","flictea c","floodM","flor)Nb","floresN","florida<","flote\\","floyd g",
"fluyeG","fly ug","folk(#}a*","fondosE","food#","fool x$#}","for uZME;2$#&c('","forjada.","forjando*","forjarse[",
"forma'${trjdba^XULIH@;87.,zG<","formó{ymQ;","formaban~B-","formacíones~","formación~qONFE-_","formaciones_","formada_-","formado|q=/","formados*","forman%iX7/",
"formar yljaWP?;/,","formaron#~uliTRGE9/&","fornaciari*","forquetina a","fortuna(","forzados,","fotonovelas{","fotos w","found&","fragile w",
"fragilidad,","francés_L","francófona 7","francesa]","francia^]","francisco_","frankNL3","frankie/","franklin q\\P65)","franquistaU",
"fríoK","freddie i","free wli5","frenéticoY","freno 1","frente&%#|xoWN>8","fresco/","frescuraONy","friaW","frialdad%",
"frida%","friendF6","friendsEi","frios 8","frivolidad'","from#xP@?$#9)","frontier<","fruto 9","fue'zurqmhgb^\\ZXPOMJD;&(jd`_]T?~E9[","fuente l",
"fuentesO","fuera'=","fueron$~ywl`[N3('&E","fuerteX","fuerza{trd][UJ>8541'","fuerzas_O","fuese`","fuga[","funB","fundíanX",
"fundadores_","fundamental i&","fundamentalesQ","fundamentalismo[","fundar r","fundiéndose.","funk~zhVGF5.'>","funky~TJG>D","fusión(WNF>","fusiona%",
"fusionando\\2","fusionar?'","futbolL","futura j","futuro$rb[","género*(\\VN","génerosE:","gómez=","gafas p","gaga i",
"galardonadasZ","gama b","gamble tT","ganándoloP","ganó kVL6","ganadora 7","ganadores 1","ganando aI","ganarK","ganas 1",
"gangF","garay_","garcía mH*X","gardeO","gargantasT","gary u","gato n","gaviota+","gaye uPF9[","gees/",
"genéticaX","generaba[","generación;63/&v","generaciones(kfV0","general c*","generation h","generosamenteT","generosidad(","genial zhNC'","genialidad%gHF'",
"genio h","genios,","genteY","gentleman(","genuinaE-","genuinamente 8","genuino vi:","genuinos&","george(\\DC","georgiaME",
"germen-","germinandoE","gerry 6","gestos k","getT1c[.","getsemani 4","gett h","ghettoC<.","ghettos[","gibb/",
"gibraltar)","gig g","gigante a","gigantes,","gimme%","gira sa;-%$^","giras pkHC;^","girl(G30:","girlsLf","gitano=",
"give x[GC.","gladysE","glam$:","glamour qo","gloria('","glorias z","go ifcB93#@7","goffin 6","gogh yO","goin\\",
"going[","gold uMw","goldenL","golpe i,","golpeaban;","goma$","gone>","gonnaG9r.)","goodT$#5","goodbye|xE",
"goodnight 0","gordon w","gordy[","gospel(cTE5'r","got[Y6tpE5","gotta 31","goza n","gozaderaY","gozar'","grabaciones r",
"grabado$^","grabados;","gracias}{tqa`\\[WLI@+&(]8","grado#","grammy(&#zvc^\\ZVIEDB=;610'a","grammys#}|nla[TQLC7/(","gran'#~idc`XUQPG3.)&}rke$","granada^","grand$#","grandeF4)",
"grandes*'}rqpdb^[WQPFEC?;5-)+","grapevine[E","grato?","grave k","gravedad 1","grease/","great g","greatestC","green 9'","greyP",
"griega+","grito r","groove>","groovin#","ground~v","grove}","grupo%#~tqmlihfe]XWQOEA?>31-+%&$}ywogaNF8&_B/;","grupos#{geRA1/*&$","guía_","guerra[K",
"guerrero a","guess@","guille*","guilty/","guitarra&%aIC*&u","guitarras iS?;","guitarrista id=;*N","gustadoH","gustavo a","gusto#x^V",
"gustos r","guy o","gwendolyneL","gypsyB","ha(%#~{nifd_]ZWSRPOKGDA:8740/'skL5+(*^)H","hábil 0","había xa;","habían,","haber)vA74","habernos(",
"habichuelaN","habiendoV1","habilidadesP","habilidosa c","habitación]","habla&kE","hablábamos[","hablamos kT","hablando|vI","hablar&rS*g~",
"habríaH-","habreís_","hacía%,","hacíanC","hace vsgY3","hacen%q`","hacer*%{aFC","hacernosK","hacerteX","hacia{zurg]ZGEB",
"haciéndonos r5","haciéndose=","haciendo pgC<S","hadJ5","hadley u","haga_H","hale q","hall&EB5)","halo z","hammond)",
"han*'%ytsoj_ZOG;:964-,(&#VL*%","happenedE","happening[","happiness'","happy\\","haráU","hard z","hardest@","hardline z","haritzO",
"has_,>","hasta(&$#{sda^ZTMB?:10-'l_","hate 7","hauser#","have(&f","haven&","hay(&lkUGA@2&","hayá(","he 5","head w<",
"healD","healing[","heard[E","heart wP@1$#fd'7","heartbreaker/","hearts 5","heavenM9/$#","heavy-&$","hecha xr","hecho*'snkeVSPGD6,%(O",
"hell&","helloQ","hemorragias s","hemos{","hereC5gc9","herederosO","heridas aH","hermana 9","hermanas w_","hermano uE",
"hermanos~|/&$#-","hermes-","hermosasV($#","hermoso d","hermosos 6","heroína,","herramientaH","herramientasC","heterogéneaU","hewson&",
"heyL","hicieron xgZD?><$","hieloT","hierro,","high&[","higher v","highway&","hijo^]N","hillsPM","hilo'",
"him 7","himno&rU^","hipZ1\\","hipnóticos 3","hippieJ","hips s","hispana kO","hispano sa]SOLI+)y","hispanoamérica_","históricos_",
"historia)&~n]UL:76/,&%","historias`0","hit 9","hitos_","hizo|xa\\PNL9.-,","hodgson x","holding z","holler[","holliday q","hollywoodTE",
"hombre*($he_TKH)('$#[+r","hombres 5","home xr93t","homenaje=,","homenajeaban u","homosexual&","honestidadK","honor`","honoris(^","hooker(",
"hopZ1\\","hope c","hora(~z,","horasR","hospitalH,","houseF9","houston)","how de/'","hoy)kjda_]C8-+(","hubieran 3",
"hucknall t","huecoUKA","huella zqm","huevo$","huff tT","humano)","humanos&r1","humo|","hung w","hurt 9",
"hurtinT","hurts l","iâ€™m 5","iâ€™ve d","iba~z^L/","iberoamérica 4","icono{","icteria$","idóneaH","identidad qjVSN",
"identificar]","identificaremos k","idiomas]L","ido tG_H*","ifMEwtz","iglesia l","iglesias)L","igual f_^ZQPDB>L/","igualdad&r","igualmente~w\\N",
"iiZ","il*","ilegal$","illán m","ilusión b","ilusionarseX","ilusionesE","imágenes*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","imán q","imagen$~p][JD@:%",
"imaginaciónX","imaginationE","imborrable 9","immortality/","impávido h","imparable^","impasibles k","impecableZ","impedido 4","impedieron y",
"impedimentos)","imperio(","impidió d","implicación 6","importante&h_","importantes bJ;/","imposible a4/%$#H","impregna$#","impregnándonos)","impregnó a",
"imprescindible x","imprescindibles?","impulsó^[","impulsaron z","in&MJCB<;3xwpdc>/)(&g","inadvertido 9","inalcanzables_","inamovible p","incalculable,","incial-",
"inciales i","inciaron}","incluía/","incluida}l","incluidas^","incluido(;0'","incluso'|a_\\PL:-%(5","incluye 0","incluyen/","incluyendo*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#",
"incognitoF","incombustible k","incomprensión&","incondicionalV","inconformista$h","inconfundibleI=k","inconfundibles%","incorporó 1","incorporación}_","incorporando b",
"increíbles%H4","incursionar\\","india$#","indiferente 3","indiscutible~","indiscutiblesD","indispensables<","individualidadD","inducidosE","inevitable sD",
"inexorable%","inexpertaP","inexplicable;","infante y","infartoHU","infierno-","influencia zpia\\X9","influenciado}9","influencias\\J?","influido f",
"influyó/","influyendo.","influyente%","influyentes{vr]A:'&","información vt","ingeniería&","ingenio&","inglés oa_-","inglaterra w(","inglesaG?)",
"ingredientesF","ingresóB","inicial}y","iniciales l\\","iniciando=","iniciarQ","iniciaron%N","inicio*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","inicios wuts;","inimaginable r",
"inimaginables_'","inmaculada+","inmediatoD","inmortal:","inmortalización.","innatas`","inner[","innovadores?","innuendo i","innumerables%",
"inolvidableU","inolvidables b4,)","inquietudesX","insaciableX","insanityG","inseparable@","insertarJ$","insideC/","inspiración&lOF?8","inspirada)+",
"inspiradas%%","inspirado v","instante d","instinto{","instrumentación%","instrumental a","instrumentales#","instrumentista(v","instrumentos zlR?","insuficiencia$",
"intérprete)","integrante+","intenciones j","intensidad r+","intentaseP","intento$]?","interesantes<","interior#d\\8","interminableL","internacional sL8-*",
"internacionalesG","internacionalizar$","internacionalmente k","internos y","interpretaba[","interpretación zkcZD=/4","interpretaciones#rkbY4'","interpretado t","interpretar zbI+","interpretarla 4",
"interpretativa{d'","intimistaX","into 7","intoxicación&","introducidos&","introducing z","introspecciónM","intuición s","inusual^","invitaF",
"ipiña_","ir l","irónicaH","iris}","irlanda(PM","irlandés(","irlandesa(&","irradian 8","irrefrenable z","irrepetible h'",
"irreverenciaH","is*)('&%$#~|{zyxwvutsponmlkjihgfecba`_^]\\[YXWVUSRQPONMLKJIHGFEDCBA@>=<;:8654320.-,+*)'&%}qdZ?971$#rT/(","island<","islands/","isn v","isnâ´t v","it}xrlGE7%pf[@61)$#~","itâ€™s l","italiaL","italiana'",
"italianas'","italiano*'_5","italianos*","ivan(","izaskun_","iziborP","izugarria*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","j1sa1t3mJ","jóvenes{P","jaén k",
"jackson#~Q","jacksons~","jamás d`4","jamiroquaiG","japón k]","japonésL","jarabe 8","jardín j","jarreau(","javier y_",
"jayG","jazz jcVTNMI>=<2GFC(#","jazzman 6","jealous o","jean sF","jesús%","jesucristo 4","jesus}D","jillP","jnvy7srofq$",
"joaquínH","joaquin y","jocelynF","joel+0","john(uieE)@?","johnson&","jones*","josé%N=_I","jose]-+","joshua&",
"jossJ","joven z^PJ","jovencísimaZ","jovencita{","joyas vt,","jr&","juan%j_N8K*","judaísmo[","judio 5","jugadorL",
"julián$","julio)L","juntó[","juntaba a","juntaron y","juntarse 9","junto{rqgbaXSQOE<;862,$#m","juntos y","just}vM.|5","justaH",
"justicia`","justo[","juvenil j]","juventud'PL,","kamakiriad<","karen|","katieM","kayG","keeble u","kemp u",
"kenny}t/","ketamaN","khaledN","khan\\","kiki@","kind i","king q@?6","kiss hq","knightE","knopfler;",
"know l$#t","koolF","la#upcSJ20$#woml@1*%|xtWQG:*'vkjKID>;86)}zih]ZYVTN<93)yfed`\\MBA&nbU=75.'qgPLF({XO^EC4~_/+([H,?-sr&$a%","lópez y","lía+","líder t","ladera`","ladoV=a_","ladyT;n","lafourcade a",
"lago%","lamentablemente%U","límite;","límites a","landslideB","línea{[","lanois&","lanzaA","lanzándose w","lanzada`",
"largaT/,$-","largo tpnfL?/.+","larry&","las)'zxvuqplkiha`^]YWVUTOMJIGD@>;430/-,*&&}|{wcbZXH<:721((~sg?%rf[+_EB","last?.","late 6","lately(","latente].","latidoSU","latin^",
"latina{snkja","latinas{","latino{sbaYVI","latinoamericano`","latinos aI=","laura'nP","lava t","le(rnhgc`_\\[YTH0+)$#w^.,$","león(","lead 2",
"lealH","learnG","learning g","leave xu","lee(qj","left f","legado(nhNE4","legal$","leivaH","lejana d",
"lejos{P","lenguaO","lenguajes}","leon t","les~}tl_]SG?>83-&#fO","let c[P@1.&z>:'","letra}w-+","letras(%#lg]XQOHA@*%","levantar]","leyenda nk[L,",
"leyendas v","leyreO","libertad`N-+)","libertadesU","libre b","lider~jA;","lideradaGFE","liderando we","liderazgo x","lie s91",
"liesB","life c@;:#vq","lightI?","likeM$#T6","limpia|","limpiamenteM","limpias c","linares k","linda$#","lindsayB",
"lingua_","lion(@","lionelQ","lisN","lista|L/,+&","listas}urf_EB","listen}","little xdBz?)9","live(","livin?",
"living e","ll uZ~T","llama t-","llamaba:","llamaban_","llamada$xP.","llamado%~laF93.","llamados_","llamandoW","llamarH=",
"llamativos 3","llave 3","llega a","llegó fT0re","llegadoL","llegando*sqfXLD2N","llegar{l_XPMA","llegarían j","llegaranD","llegaron z",
"llena{hdca[P>2","llenóU","llenando i1","llenarnos@","llenas*%pdXVUQ@>$#","lleno(whZH+","llenos|qomcJ(3","llevaMGF2$a","llevó[UH6.,","llevaba\\D",
"llevadoD","llevan kS","llevarNG,","llevaríaX","llevarlaP","llevaron~[","lloraO","lluevaK","lluvia%h","lo*)vutpnjihfe]ZYTQPMKHF@?=;9873+&%zqkb^US:/-,~}_LD.a$[",
"loca_","localizarlo l","loco y","locura z_O","loggins}","logical x","logos*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","logra e","logró d\\[E","lograbaD",
"lograban 9","logrado&_Z7504","logrando&ca]ZIED","lograron'k3/-","logro]","lokosN","london?","londres if;$(","lonely p","long xuQ&}|ed",
"look y'","looking&","losZYWMKIFD@<82$#}{wpomkic`VPJA75+)(%#xvsqnjhge\\XTQG64,**)&zutfbaOLH;:93(''$~ldUSREB?=1|]N0.y[>-%rC^/&_","lose w","losing l","lotta&","louT","louisiana$#","lovable r","love&}|wvpolid[ZQB9621('D?>;5qJC7T/.",
"lovedL7","lovely v","lover(","lovin 5","loving zB5$#d","lowe f","lt[","lubna`","lucía^","luces[",
"lucha$,","luchador r","luciano*7","luciendoH","luego:","lugar&zsb_\\S>&","lugares a_4","luis-VUK","lujo vpm`PC","luna a](",
"lute 3","luz{`QK(zR","m7v55glqria$","ma 3","mágica?","más(yutrpmljia_S@>8652+*)&%|{xnfed^[ZYXVUHGC?;:-*)(%'#shbTNBA=<941/,~vJED'}zkg&L7]","máter q","máximas/","máximo>","máximos ea",
"méxico`^a","módulosR","mónica`","mañana%","macB","macorinos a","madre)&","madres w","madrid^NH","madrileña$jN",
"madurezO","maduro]D","maestraRH","maestría&#'","maestro(HC=.(","maestros%C","maggieW","magia zqpoGFE?5d","magic i","magistral 0",
"magnetismoO","maitreya z","majestuosidadC","make[B6","mala,","malagueño 8","malcolm&","malo-","mambo#","mamma%",
"manTC@%l0","manaK","manantialesC","mandolinas l","mandos&O","manera zr'G","manhattan#","manifestaciónE","manilaU","mínimaH",
"mano c^W5","manoloX","manos waD","mantener[0+","mantenerse&Z","mantenido-","manteniendo i","mantienen-","mantuvoUO","manuel^+)",
"manzanera o","mío{","múltiples[","música'&%$}|zxspmkgd`^YUSPMIEDA976210-,)('*~{tifeb\\XLHF@=<3&%(vnjha[K>:4qC?/r","músico neXQ,)w","músicos(r^[>.$","maquillaje]","mar{aL=*U","maría 5","maravilla>",
"maravillándonos 5","maravillarnos.","maravillas%","maravillosa=+","maravillosas}C2","maravillosoP","maravillosos#","marcY","marcó j[6/","marcada qm]6",
"marcado%VR;","marcando%;","marcar/","marcas*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","marcha aE","maresA","marga,","marginados 5","mari]8+","mariachiV",
"mariahZ","marido{","marineroA","mark;","mars:","marta*","martínO","martínezO","martha[","martin u",
"marvin uPF9[","mary\\","marzo^","mas r","masas k","mascar$","masculina z","masqueradeC","massachusetts/","massielU",
"místico zR","matices bC<","mítico i[F>;","matter 0","matthew w","matthewman q","maunickF","maurice>/","mayWi","mayúsculas^",
"mayo k,","mayor)'#ulb]Z4","mayoría&dOM","mayores s[ZTL","mayoritaria r","maysaF","mcaE","mcdonald}","me#{xvspicYTRGCA@5.&%$#_[SQHE72'zyr]J?96tL","mecanoO+]",
"mechanics e","medallas^","media^","mediados~wtfU?0","medicinalesF","medinaXR","medio ufa>,r[","mejor%ecZXKEBz","mejores)c_[WE>+*0","melancólica t",
"melancólicas%","melancólico+","melancolía eH5","melina 4","melodíaXHF9+","melodías%}mfQN@%$#","meluaM","memoria kiX?<94","menZ","mend'",
"menos yN","mensajeraX","menta*","mente h&","mentes qh","mentiríaG","mercado zMA3`P","mercuryJi","mercy[","mereceY",
"meridianos)","meritorias?","mes`H","mesaVn","meses aUB","mestizaje jNC8","metal&","meteórica d","metro a9","meverse 1",
"mexicana a{","mexicano a","mezclaM","mezclándose 8","mezclaban?","mezclan h","mi'z]XVKG98+*kYS,)4","mia%","miéntemeN","michael#\\~}QD",
"mick t","midnight[%E","miedoW","miedos,","miembro&g_","mientras ydM","miguel^V","mike e^M","milenio lJ5","miles*)",
"milk 9","millónEn","millionM","millones&nlkgf^]VLGD?;74/)*","mind f","mine dFT","mineápolis h","ministro[","minute}","minutos g",
"mio+","mirabaU","miracles[","mirand{","mirar[","mis#a=(X","miseria[","misil 1","misma_P","mismísimaP",
"mismo{zm_;31-","mismos+","missM","mississippi(r","misteriosa p","misticismo z","mitad z","mitificación l","mito~b%","mitos_",
"mmmP","mocedades_","moda jf4","modelo s","moderna j","moderno]","modestia'","modulando'","mojados 8","moldeaba.",
"moldeandoG","momento}xdE/_","momentos&}U","moments x","mondays|","money g;","montaña`","monteroO","moon l","moondance(",
"moonlighting(","moría r","morada-","moral['","more|zoD/9","morena{","moribundo r","morir r$4","moriria*","mornin(",
"morrison(","mortis z","mostrar`","mostrarnosG","motivadosD","motivosH","motownQ~IE[","mottola{","mountain[","movement l",
"moverse~1","moviéndose dE","movida$jN","movimiento u^","mr d","mtv l*","much@/$#","mucha a","muchas)(vtfed+'H","mucho*aSP.~",
"muchos&%ypn_\\YHC@>9753(%{s","mueren^","muerte&#rpihb[($9/U","muestraRQF9","muestran w@","muestrasZ","mujer sca\\PE65{]","mujeres s5","mullen&","multi(vJ",
"multinstrumentista 2","multipremiado 7","multitudinaria^","mundial s94-","mundiales k)","mundo*'&zunifb`_^]ZYXNKIG?;:742-&{sa\\VSL","mundos)","muralla+","murcianoW","muro g%",
"musa q","music{sne.}o`L","musical)}sofecb`]\\[UTQPN=<410/+*'%$#{yj8(aO","musicales~{vtc_XUJC;9*%","musicalmente$tX=","must(i","muy)%zpokf`YU?<;2{S","myPI@<21vlE$#wfed.7","myself 7","mysterious&",
"mystery p","nacha,m","nacho m]","nació wUM$#","nacida s7","nacido k","nacieron@","nacimiento vaI)","nacionalP","nacionales*",
"nacionalidades 3","nada e4)","nadandoY","nadie 3k","name&z","nâºU","nâº1U","número{wrpfa]\\RJIB10-&iZE^$","númerosZQ%&D4","naranjo`",
"narea m","narración`","nasdaq{","natal^P","natalia a","natasha{","nativa$#","nativo(","nativos a","natti{",
"naturalXTC6G","naturalesO","naturaleza nb=","naturalidad%","navajas]","navega a","navegando r","navidadI","necesariaPF","necesarioQM",
"necesidadX.","necesidades a","necesitadoF","necesitoV*","need[)","negra r[ECj","negro}ec8.r","negros d","neil f","neitherE",
"nelson hL","neoyorkino z\\","neoyorkinos#","neumáticos.","neumonía,","never$#T).","neville$#","new$#uh]w<","newton?","niNH)",
"niñaO","niñeraP","niñez a","niño vU","niñosT","nicksB","nietoN","nigel m","nigeriana q","night(wCB&pQ/",
"nightclubs=","nightfly<","nights 5","nigor z","nikita@","nina q","nineM","ningún(","ninguna qkV","nino b",
"nivel_Q;+<","no*(#~}zrpmjife`^]\\VUPOHGD@>81/.('%$#&ysq_[XRNL3-,$kC'{a9","noche^=%k","nochesH","nocturnoE","noelia b","nombre*)'zmlja`^G;/$#h_~","nombres*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#]","nominaciones aI=","nominada c",
"nominadoJ","normal y","norman u","normas g","norte)M","nos#yxwhb_VR;:741/,|UMHF()","nosotros&,","nostalgia&|=","not 9","notable wI",
"notablementeB/","notables~","notasFG","nothing h;2(","nothingâ€™s)","notoriedad'","novena^","noveno_","noventa 9","now i7xtd)",
"nube*","nuestra kie4","nuestras)k","nuestro^ZSe","nuestros&lPM:","nueva&#z`_OA<9$#","nuevas aC:%","nuevo$zmlXTPJHBA95/[&","nuevos)(~_N%`","numb g",
"numerosas'ka^","numerosos&nfGC=;/-*)D%","nunca a54^X","nutriéndose q","oídoO","oasisN","obús$","obraRH","obras%","obsesiva'",
"obstaculizó 8","obstinada[","obstructiva$","obtenidos%","obteniendo}","obtuviendoM","obtuvieron}3","obtuvo p","océano#X","ocasión%",
"ocasiones*zpH","oceanía s","ochenta u(","ochoM","octavo?","octubre#w","ocuparO","ocurrentesH","oddity:","odioso z",
"of iZLCB@<9)%&#xvqleFE>7530.'wdc;","oferta-","off h","oficial s","ofreceF","ofrecer k","ofrecieron}","oh op","oido'","oidos#POM",
"ojalaK","ojos[=","old o","oleajeH","oleta c","olivia?","olvidéL","olvidar{iIE<","olvidarnos#","olvidarte]",
"olvido 4","om5$","on zxwroicGC@:5$#~lgfd[J97Q2","onâ€[","once|","onda f","ondas^","one lic\\ZED6%&","only u|p","open 2",
"operaciones${","operator q","opportunities f","oprimidos 5","optimismo m","options*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","opwudidgv1eJ","or 2&(","orígenesE-","orbison p",
"orchestra$.?","orden(","ordinary q","oreja yO","orgullo r","origen 5","origenes r","original 8(","originalidadRF8(","orleans$#",
"oro ke^LI=","orquesta$.","ortodoxo[","ortodoxosN","oscar|Q","oscura t","oscuras p","oscuro th","oscuros z","ostentación'",
"otis rP5d","otorgó[","otorgados n","otra)aUA&%_^","otras*)%}zda''","otro ma_LE?=;.,","otros*)('&%$#~}|{zyxwvutsrqonmlkjihgfedcba`_^\\[ZYXWVUTSRQONMLKJIHGFDCBA@?=<:987643210-,+*)('&%$#pPE>;5/.]","out l</","over oe","overture x",
"own fB","oyente 6","paI","páN","página vt","pájaros$X","pálido p","pánico$","pérdidaU","pócimaF",
"póker$","póstuma d","póstumas p","póstumo d","pabloO","padre 9&[","padres a","pain dD","pais s`P","paises^",
"paisley h","palabraH","palabrasRH","palacios%","palmarés v","palo 8","paloma+","palos 8","palpable i","panalK",
"panchoH","panchosS","pange_","panorama)yjb`UON+*","pantera`","púa;","púber~[","público c^XDC9*","públicosD9(","púrpura h",
"papeles 8","para*)'&%~xwvsphf_]\\ZVOKJFEDB@;:.,&{zm[YTRQMLHA?541/)ylaXWI-9$`P","paró 9","paradógicamente[","paradise q","parado(sk","paradoja_","parar f","pararon f","parecía zQJ,&",
"parecidoG","pareciendo d","paredA","park h","parroquiaR","partícipes r","partículares o","parte&%|{unja^[ZXUTQPHEB?;7631i/,","partesQ.g","participacionesL",
"participar-","particular*tpdXHE;:2*,","partir&L","partonL/","pasó$9#","pasaba&$U","pasaban k","pasado[A","pasajeH","pasando%",
"pasar[7","pasarán v4","pasen&","paseoE","pasión+(z4","pasionesS","paso%zo`I4k_%","paternaU","paul&$qFe","pavarotti*7",
"peabo 7","pearls h","peas 1","pecesH+","peculiaridades>","pegadizas%","pegadizos l3","peggy q","película yT?7/","películas k%",
"penaYU","penetrabaT","penetrar 5","pensandoI","pensarR","people a","pepeN","pequeña{`","período l","percató.",
"percepción+","percusión%[","percusionista>","perdóname 4","perdedor$","perderOGC=","perdidas`","perdido g]X","perdudarán,","perdura o",
"perdurará 4","perfección(","perfeccionándose$","perfeccionarR","perfectamente qe","perfecto qB/-'","performingM","periodo a","periodosC,","permanecer rh\\",
"permanecerá{:&","permanecerán k","permaneció}","permanecido#","permaneciendo]E","permiten%","permitióO","permitido#t","permitieron$","permitir~",
"permitirseC","pero*(&%#~|zxsnmjdba`^VTQPLIED;8,+(&%'h_[NJH'9/","perpetuoS","perro j","persona n[U","personaje`","personal zbaXC","personales[B","personalidad ka6","personasL@",
"pertenecía ud","perteneciente'g_U:76","pesadilla d","pesar m[","pese sihb\\Z2","pet f","pettigrew 9","pezA","phil o%","philadelphia tT.",
"philarmonia$","philip>","phunk 1","pianista cP@60","piano{aP6+0","pido+","piece 9","piecesF","piel){j2","piensaS",
"pienso)","pies s","pieza&","piezas#<","pilar[","pilares s","pinceladaH","pink g","pinochet w","pintorU",
"pintura$a","pionero[","pioneros tplT3","pipsE","pirataH","pisó{","pistas~gf1","pistoletazo d","pitiful d","plácidoL",
"plásticasX","placer_","plagada[@","planeta{31/","planta)","plasmadosP","plasmar,","plastic:","plateroA","platino a\\LJI=",
"play.","playback a","plays$#","plaza y","plena t","plenamente g","pleno kNF/","poéticasX","pobre\\","pocas vsd\\H",
"poco rmlh?9~^*","pocos ebY<4t","podíaJC","podían>","podemos#dGD/(","poder nW65.H","poderío`7","poderosa z\\5","poderosas{b","poderoso{qi[-",
"poderosos_*","podido#","podría&oe]XPK","podrían 7","poesíaXH@+K","poetaU,","pokito 8","poko 8","police w","polifacética s",
"polifacéticasV","polifacéticoY","polpularidad]","poner\\[","ponerse&","pop&~{xusqojhfca`^YXVQODCB?<;:6210*)(}yrZ9,m]","popular'w/","populares'","popularidad#naXLDB?4/","popularizóUTE7",
"popularizaron%","por ywunmhgfedcb`WVRQPNLKC>;87650.''~|z\\[JEA?<:431-$##}tXIFD=+*(&%&${qkU(rHG9a^,_/","poros,","porque[H","portal*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","portetX","portuguésL","posee e","poseedor$tTI'","poseedora c",
"poseedorasQ,","poseer vbQ<","poseerlo z","posibilidad 9","posibleVC1","posicionaron f","positiva>","positivismoF","positivizarse 1","poso 3",
"posteriores zJ","posteriormente c","potencial{","powell$","power h7","prácticamente&<3","practice.","príncipe z","preach.","precariedad[",
"precie&","precioY","precursor.","predestinada\\","predilecto^","predilectos(","prefieroX","preludio$","premiado#T","premio(zZJIE1'",
"premios(&|wvlkifa^\\VPMLDC=0/n;*","prenderse'","preparándonosR","presaP","presagiando r","presencia a1","presenta)","presentándonos)","presentó<","presentabaZ",
"presentación=","presentado 4","presentaraP","presigioso;","presitigioso)","presley p","presto=","pretenda<","pretendíaJ","pretender h",
"pretty p","pride&","primer}rpjZV93/)$aI","primera{sg/-","primeras rF","primero r0","primeros ok^]U&","primo m8,","primosE","prince sQNh",
"principal>","principalmente}H=3","principe[","principio l_[H","principios yxhT?","prisoner 5","privilegiada 7","privilegiadas\\","pro)A","probablemente^",
"problemaN","problemas|yl\\D,","procesoX","procesosH","prodigio v","prodigiosa+","prodigiosasE","producción yfD?&$","produccionesM","produce_$",
"producido m<","producirse z","productor$vd_\\WL;54)%","productora saP","productos{","profesional ka^","profunda kJ'.","profundamente j","profundas%N","profundidad%C",
"profundidades c","profundoT7'd","progresivo%xgR","progreso n","project a","prolíficas h","prometedor$","pronto~k","propia(|zr_.","propiedad*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#",
"propio(&_W%","propios(","proponeY","proporcionó#l","proporcionaban>","prosiguió a","protagonistas a","protagonizando{","protesta rU","provechoD",
"proveniente d\\","provocación k","provocador@:","provocadora&","proyección bQ8","proyectos{f`^;","prueba 2","psíquicos)","psicodelia zg>","psychiatrique`",
"pt r","publica a","publicó<;","publicación d,&","publicados i","publicando;","publicistasL","pudíeramos[","pudiera~","pudierasD",
"pudo[","pueblo y","puede vt\\XLH8,","pueden z","puedo]","puerilPJ","puerta%+","puertas f3","puertoriqueñoI","puertorriqueñoY",
"pues^","puesta&","puestosE&","puff\\","pulmón^,","pulmonar$","pump 1","puntaA","punterasE","punto&ype\\[O/$",
"puntos'","puntual z","punzante w","pura>","purezaM,","purgatorio`","puristas(","puro y9","purpure h","puso)P",
"putJ","qgxbbd5bve4$","qué^YI#k","quédateW","que wpjWRQA?*'$#)#tomihcb\\SMJI:50(%|xufVNK@%&{vq]T<764321+)'}ysnle`ZYFECB;.*(~XOLH98/-$rdD>PG&z,kUa^_[","quedan%|P","quedar z","quedara x","quedaría vY","quedarse>",
"quedes s","queen%i","queenâ€™s(","quería y","quererF=","quererme a","queridaU","querrás*","quién)_YPM'","quien{ws\\XO1",
"quienes%","quieras=","quiere{","quieres yR4","quiero)%zyn_R=b","quietest x","quijoteL","quilates%","quimiX","quinto&-",
"quiso$","quitó[","quizá r","quizás&z+S","récord#4","régimenU","raílesE","rabia%","radio olif=9j","rafael+",
"raging(","raices%aNJE","rain h","raining x","rains)","rainy|","raiz a","ramasX","ramilleteP","rampasH",
"randb~r)","rango(`Z","río^","ríos^","rap 1","raphael k","rapid l","rasgada=","rasgado 5","raspberry h",
"rasputin 3","rítmica>","rítmico~y&","rawlsT","ray q","raza r","razas r","re[E(","real)}","realidad#r(",
"realizó p","realización[","realizando k;","reaparece a","reasons>","rebelde y.","rebosanF","rebosante r","rebosantes%","recaudarE",
"rechazo[","recibe a","recibióE","recienteH","recogen>","recompensada^","recompensado(","recompensadosC","reconocida`","reconocido rn",
"reconocieseG","reconocimiento#w^X-*","reconocimientos i`_^VG8/*)","recopilados d","recopilatorios^","recordL","recordadas&","recordamos 7","recordar yp_","recordaréis(",
"recordaremos,","recordarte`","records{ZP9","recorrió^","recorridoH","recorriendo)","recreo,","recubierta}t","recuerdo?9:","recuperada 8",
"recuperarse$","red 9t","redding rP5d","reducirH","referencia&ogf\\","referente$b6","referentes a","referimosV;","refinado<","reflejaba g",
"reflejabanB","reflejadoH","reflejandoH","reflejarH","reflejarlo q","reflejarse 6","reflejoH","reflexión[","reflexionar a","reforzadas%",
"regala b","regalado x","regalaron|","reggae*N","registered*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","registrado_","registro p","reina{sq\\","reinhardt=","reino^M",
"reinventarse zk","reinvindicación#K","reinvindicativasX","relación)","relaciones&","relataU","relataba)","relevancia~","religion l","relojS",
"remake%","remoL","renacimiento$","renal$","rendidos&","rendir r","renunciar^B","repentina 9","repercusión 7","repertorioT?",
"replanteándose a","reportó w","reposadaE","representantes n","reproductor<","resiste)","resistir%","resistiré-","resistirseM%","resorteH",
"respect d","respectivos*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","respetado,","respetados:","respeto r","respirarX","resto k","resultado q[P","resultados`","resurgido y",
"retirada^D","retiro 0","retoma a","retomar[","retorna a","retornó`","retorno z]%","retraidos%","revés&","reverendo r",
"revistaE","revolución j[","revolucionaron y","revulsivo~PN","rey rnY","rhapsody i","rhythm c","rica%a6","ricasN","richard|",
"richieQ","rick x5","rico(n<m","ricosXC","ride|","ridgeleyD","riendaX","riendas~","rightJt","rimasH",
"ring 3","riqueza>,","ritmo*&~{ymhYWJEB81","ritmos maKID85>3","river 0","rivers 3","rnb rqc\\T9(","road$","robadoH","robar.",
"robarte=","robertaP","roberto n_","robin/","rock*($~zxplihg]RIEA><64'&j`X0*%yWB?;:}-&^","rockeros-^","rocket@","rodeaba,","rodeado z","rodearlos z",
"rodríguez%","rodriguez y","roger xie","rogers h/","rojo-","roll(&p^EB;60&y?-","rolling pNE%","románticas'p","romántico[S=","romantic$u]",
"romanticismo nS.","romeoK","romero*=","rompió{","rompiendo[","ronca(","ronstadt$#","room<","ropa{","rosaK%",
"rosasUO","rosenvingeU","rosie&","rosita*","rossQL","rot y","rota d","rotosHE","rotundo r`]","roxy eo",
"roy p","royce s","rs+","rudeza;$#","rugido r","rugosaH","ruidoH","ruiz$","rumbaN8","rumor%",
"rumoursB","run 5","running}","ruptura a","rvtvssztu50$","ryan$","s1piz1olypsJ","sí aP4","séV","séptimo_",
"sólamente d","sólas w","sólo#tn]\\LKHGF>4-+){dRJ%","sólos 4","sabía%","sabe)q^k","saberP","sabes a","sabido*WK%+","sabiendo e",
"sabina yH","sabor eSH98","sacarD","saciadaE","sad@","sade q","sagrado~","saigon 0","sailboatM","salónT?;60'&(",
"salida q_[","salido%","salir*~\\*","salmonelosis$","salsaNY","salta y","saltarH","salto~D*","salud,","sam z[r",
"samba#I","símbolo h","same o","sanOL,","sanación`","sanada z","sananda z","sanarF","sangre}{r$#","santa^",
"santiago j","santosK","sanz sY","satisfy e","saturday/","saxo u","saxofón a","saxofonista(","say vE@Q","scene o",
"school xM","scottP&","se*('&%#~}|xvurpoligebZYTRQLKJHGFDCB?<;987510%$#td_\\>/.)($yf^PN&za[Xh`,","sea&r","seña qjVSN","señorL","sean%","seasons 6","sebas*","secasX",
"sección*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","secretaria_","secta[","seda,","sedosaT","sedosas>","seducción hT","seducir a","seductoraE.","seeT.",
"seems@","seguidamente,","seguido%","seguir$~yk^[5%{","segunda zg","segundo a<,","segundosU","seguraO","seguro s_","seis rB",
"sello[","semanas}]$r","semejante(","semilla jC","semillasH","sencillas%","sencillez n","sencillo}Z","sencillosZ*","send r",
"senda^[O","senderoH","sensación 8","sensacionales z","sensibilidad*)waXMKB@,","sensible vt@)$#","sensibles p","sensitivaH","sensual q.+$#'","sensualidad q[3",
"sentía r","sentían 5","sentado d","sentidas>","sentidos rnm=.X","sentimental/,","sentimentales a","sentimentalmente)+","sentimiento rc['$#","sentimientos tdbUSQ,+",
"sentir(sX4","sentirme$#","senza*","separación<","separado y","separara x","separarme m","separaron 9","separarse a","september>",
"septiembre 4","ser~ysqpneaTOMG7642-#rL","seraI","será(","serán`","sería-","serían+","seres&r","serie|d(","seriesP",
"serpiente'","serrat^","sesenta 9","sessions s","sesto 4","set w","seven zB","sexD$","sexo[D'","sexual[",
"sexy*h-","shake rG~","shakira s","shape w","she pv","sherpa-","shinePg?9","shining>","shook&","shoot&",
"shop f","short u","should/","shoulder e","show i","showman'","shut 1","si{ztYPGF91.+SH=","sidaE","sido sVLH931",
"siempre%#kjONHGF>=74'%{z:$(q","siendo(spb\\[XMJ94.+&k{","siente z","siento_","siete`O","siglo(~snkih[T;1%<","sign z","significa-","significóK","significaba;",
"significar,","significara|","sigo z","sigue(X9/L","siguen vb</","siguió z","siguientes^","silbidoZ","silencio`","simón j",
"simbolizanS","simone q","simpatía(","simplemente#yk","simples|","simply 9t","simplyred t","sin&#{ze_^[XKGEC;731-+(qbBfHU","sinatraNL4","sinfónico xgR?",
"sinfonía^","sing|>","single l9","singles d","sinoL-","sintetizador o/","sintonía(","sinuosasH","sinuoso$#","sir@v",
"sirve 1","sirvió.","sister z","sitio,","sitios]O","sittin d","situación r;","sky g","skyway<","slave o",
"slowlyU","smooth 9q","so pC@;","soñaban~","sobranYH","sobre)~}vpnmj^VTI@7&&ta\\E*","sobredosis h","sobrenombre(","sobresalir\\","sobretodo.",
"sobrevivir,","sobreviviré`","sobreviviremos_","sobrinoN","social ra6[","sociales)","sociedadL","sodi{","sofisticación?","sofisticado<",
"sol)","solapa}","solas w","soldaditoA","soledad a^","solistaB>=<","solitario~{wrc[QD;5,$#<","soloVR&","soltura~(","sombra-",
"sombras[","somebody wi/","somethingGt","son('$#~|{zxwvusrqpomkjhgfcba`_^]\\[ZYWVUTSRPMKJIEDCBA@?=;:8765430.,*('$#*%tnliedXQONLF><921/-+)&)}HG%&y","sonaba r","sonaban f","sonandoO/","sonar<9","song x@>","songs@",
"songwriters)","sonido(&}xtZTSCB?<;982-g]WGF.%","sonidos|qohfaOFA?853jZM>G","sonora*?>/","sonorasP;9,","sonoridadX","sonoro;","sony{`","sopaW","soplarX",
"sordomuda s","sorpredentemente/","sorprendernos 5","sorprendiéndonos(b","sorry@","sosegado'","sou n","soul~vhWTJGF>:$#(tqc\\[PI2.#}zd5reEC9'","soulman[","southern)",
"soy n)kL","spaceG:","spandau u","speak#","spector%","spellJ","spencer q","spice#","spirito*","squeeze e",
"sr%","standing@","star>","stars t","start 0","started 1t","statonP5","stayPz'","stayin/","steely<",
"stepP","steve ud","stevie[LGFEBv","steviewonder v","stillF@6&","sting*w","stivel yW","stone pE?%J>","stonesN","stop i$#dB)",
"story u","straits;","stranger x","stream/","streetT","streets&}","streisand 7/","strong d","stuart q","stuck 2Q",
"su%|xwvnicSKGC3'&}tmfWND?>=8541+)yuj`_\\ZYVTPOMIBA;62*)spl]XURQLE@970(&%$#*~qgebJF/.'rk(h<z^:#aH{d,[$","suaveVB","suaves|A","suavizaciónW","subían 8","sube)","suburbia f","sucedido%","sucias-","sucumbirD",
"sudafrica s","sudamericana w","sueño l^K","sueñosHE","suecia]","suecos%","sueltaX","suerte s8,m","suficiente a]","sufrióH",
"sugerente q?3<","suicidaron z","sujetaba 9","sultans;","suma>","sumamosF.","sumarU@2-","sumarle(","sumergas c","sumieronD",
"summertime r","sumne w","sun cC@","sunny 3","sunrise t","sunshine v","super yJ","superación,","superado#,","superarU&",
"superconocida>","superestrella{","superfluasM","superior+","superlópez y","superstar|4","superstition v","supertramp x","superviviente 5","supoC",
"supuso i^,","sur 8","sureñoW85'","sureñosX8","surgían p","surgen%","surgió z<8*","surgido%%","surgieron}u\\","surrealistasX",
"sus*)'%$}|xvnmjihed_ZVTSQNMIBA?=:6540+&(&#~zyutofcb]XWURPLF><81.-*)('{sqplk`^YOKE@;92$#w\\JHGC73/rg[D%a,","suspender s","sustitución&","sustituir/","susurro 7'","sutilmente 8","sweetZ6","sweetest q","swing#;","syd g",
"tí)","tándemTB@","técnica c","término l","tómame_","tabacoH","taboo 1q","tacones$","take x$#","takes%",
"takin}","tal&zaH","talón s","talante@","talento whe\\YQPJ:'$d","talentosPC","talla e)","también'{srhe^NJHE?:9'(","tambienT>","tammi[",
"tan~}upca^]\\VPJI>96$qd4(","tangoB","tangos=","tanta 4","tantas,","tanto)#~za_]YR(","tú)saA84'VSR_","tapestry 6","típica w","tarde~<&",
"tarqueW","tatareado_","tatuó/","tatuajesH","título<","taupin@","taylor i","te*}rnecVUIHF85,*'#_Y;sb","tears c","technologyM",
"teclados%","tecno]","tejadoA","telónM","tele%","televisión|{","tell 7$#","tema)$tl]C","temática&","temas#|sqpc`_]QEB;976+)($JD/",
"temperamento*","templadosE","templeE","tempted e","ten-","tenía&J","tendencias:","tenderness d","tendido)","tenemos(",
"tener{zaB-","tengoYI","tenido~{a","teniendo kB","tennant f","tenor p>","tensionesB","tentarS","tequila y","tercer zu*",
"terence 9z","ternura|UMH,","terrell[","terrestres)","tesoros,","textosX","tez t","thalía{","than o/","that 7@>)E",
"thatâ€™s d","the(zuoecNMFB<31/%|wvtqhPLD0)#i[5&xdQEC7}plg$#@~.>","them wgM","theme*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/-,+*)('&%$#.","then 7","thereZTF&~","these d","they w|@","thing*F?5tTE","think 7",
"this ofC(","thomas w","thrill&","thriller#","through u[E","thunderstruck&","ti)mIH","tiñó h","ticket|","tiempo%$zrg_ZA%X",
"tiempos z_]EB/0","tienda zf","tiene}zqeaYsR","tienenA","tiernoS","tierraW.","tigre$","tildando e","tildar t","tim#",
"timónH","timbiriche{","timbre*seV5&$#","time l?","times$#","timonelH","tina)","tino$","tinte t","tintes l",
"tipo n","tirados$","tired'","titanic 7","titubeantes[","titulada*T","titulado zlI/*","tiza j","tkdmiyrmbik$","to vurpogPLJG6/~zifd[TD@9&#}?|E",
"tocándoles?","tocándoteH","tocó^","tocan t","tocandoR","tocar zP;","tocarte j","toda qnjed_[CA65/+'&^","todas)({<9fG","todavía zvdU",
"todo*$~|vtlj\\YQPNIHGD<3-+*')(}rpnm_VUTSRLK@?74&#[Ea^","todos*)&%$#~}|ywvutsrqponlkjihgfedcba`^\\[ZYXWVUTSRQPNMKJIHGFDCA@?<;:87654321.-+*'&%$#('{xm_]OEB>=9/,)(zL0","together('","told(P","tom*","tomando~","tommy{","tomorrow 6","tonada a","tonalidad e",
"tone#","tono p","tonto j","tony u","tooG/dD6","top-","topamosF","toque*(zt80&","toquesX<","torpedee 1",
"torroja]","tortura s","total a","tour$#","tozzi'","tráfico%L","trágico$","trabajo 9B","trabajos)(yxaPB*z,","trademark*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#",
"tradición 5","tradicional(B","traen?","tragedyY/","train z}E?","tranceR","trans<","transcurría z","transcurreU","transfer#",
"transforma`$#","transformación~","transformado~","transformaron z","transgresor:","transmiteYU","transmiten y1","transmitir(e","transmitirnosI","transporta r",
"trío/","trapecioX","tras){spm`][UTOMLHE<;:-hba9","traslada a","trata&","trataba[J","través)('qg,*$#","travesX/","travesíaH","trayectoria i[U@0'",
"tree&","trenE","trent 9z","tres|mkg`US;","trianaXR%","tributo r","trickle#","trioS","triste n","tristemente 3D",
"tristezaJHB,","triunfaY","triunfando=","triunfar{`_","triunfo s%","trompeta=","troncoso%","trouble.","true u","truhanL",
"trulyQ","truncada,$","truncado bL","trust 0","truthP","try dD","tu hK,%U","tunnel;","turnC?","turner)",
"tus rVO","tutelados+","tuvieron|W","tuvo up`[.","tv(","twice 7","twilight#","twist a","u2\\&","ulster(",
"umberto'","un*'yugfcYWVTQJ61+$#xvsqphe]NIGC>=832.))#|tmlid\\ZXRFB@<40/-(%~{wnkb_K;,&&`PLE?'%rUS}z^H(a[D9$","una)(wupog\\XVRQJFB?=:30*('&~}|vtmihfPOMGA954%*$qje`]ZWLD@>87/-&{ndcb_T<6.%z;,+'raUHE^[","uníaC","unas%z`_\\SQH&","une]","unicef s","unida+","unido)^VM","unidos#ka_^",
"unir(","uniría&","unirse-","universal)nL","universales*","universalizando}","universidad^(","universo*","unlimited.","uno*)'%#|{ztsngfedb_^]TOLA>=:7630/+*('}vra[CB?1&",
"unos%|_WM>3*[","up[P#1.","uptown 0","uqyy4nglewuJ","uranga_","uranio k","uribarri_","us gE%)","useE","usoH",
"utilizó a","utilización f","utilizando?","uu{","uvi$","va sYML","válido*","vía 5","vacio z/","víctor^",
"vídeo*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","valíaY","valióY","valli/","valoradoC","valorar p","vamos m","vampires z","van ym^;8O-(","vandellas[",
"vanguardia$","vanguardista:","variable(","variante{","varias}{tk`\\VPFC0+$","varios($}la\\[WTQMDA;76","varita?","varonaH","vas=","vítor)",
"veYL6|E","veían 6","veces%kbM","vegaNm,","vehículos.","veinteañeraP","velloU","velocidad;","ven{S","vena$t",
"venía}","venas}rc1$#","vendaval|","vendedor_","vendedoresL","vender kgf]GD","vendió^","vendida/","vendidas l*","vendido z]VL/)",
"vendidos&nB;764&","vendiendoE","veneno j","veneradoH&","venideros~","venta u","ventas}{sa`\\-?","venteN","ver jdWH=","verán`",
"verano^O*","verdaderamente h","verdadero h.","verdaderos r","vergelS","verle d","versátil(","versátilesV","versatilidad{","verse a",
"versión+","versiones'_^JC","versoH","vertiente)","vertiginosaL","vez)'&zi`_A52/r,'","viñaL","vió bL,$","viaje mH@","vibrante'",
"vibrantes>","vibrarK","vibrato.","victim 5","victor)+","victoria,","vida*&$|rqdba_YXUTSIA>=<54/.{-^[LH","vidas k9","video$","videoclipsG",
"videomúsica*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","videomusica*)('&%$#~}|{zyxwvutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","videos*)('&%$#~}|{zyxwvutsrqponmlkjihgfecba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#d","vie$#","viejas z","viejoN5","viejosE%^","viento l","vieras=","vigor 9",
"vigorosa i-","villa=","vinilos%","vino c","violín=","violines?.","virtualG%","virtuosa(","virtuoso mIC(","visaK",
"visado_","visión&","visiblesE","vision xZ","visionario([","visionsZ","vista/","visto^","vistosidad 3","visualizar[",
"vital^G","vitalidad m>","viva k<-","vivas v","viveA","vives s","vivió 3","vividoH","vivir$Y8L4","vivo{T:3&",
"vocación r","vocal$#}{ze`\\95'&$#cZ","vocales#sr`\\OC7_","vocalese#","vocalista aB8*&$#O","vocalistas dcF3","voces)'&eWVSPFE9+*b_%","vol s`","voló c","volcán t'",
"volcaseL","volo*","voltage&","voluntad s","volverE","volverte=","volviendo/","volvieranB","vos*","voz*(}|utsrqponcbZYXVTPJIHEDB?>:7521*$#%z[M4+'ked=(.",
"vu s","vuelo+","vuelta r","vuelvo y","waka s","waldo^","walk;","walker m","wall g","walter<",
"wanna[","want iZD~","wantsE","warwickE/","water}","waterloo%","waters e(","way xB7.>","ways&","we liQ0(|9",
"weather<","weaver/","web vt","well z","wembley(","wereMEg","west f","whamD","what xrfME<2.&}['","when uTG)",
"whenever s","where&719","wherever s","whisperD","white>.","whitesnake-","whitney)","who z","whole&","why(@",
"wild(","wildcard z","will i617","willieL","wind>","window*)('&%$#~}|{zyxwvutsrqponmlkjihgfedba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#c","winner%","wire$#","wishTg","wishing z",
"withJ@1.&","without\\Z&","womanKEpc6/","won 2","wonder[LGFEv","wonderful r","wonderland>","wondersB","word`@","world rlQL<>",
"worryF","would 9","writer;","wrongJ","www vt","wyclef s","xabiO","xanadu?","xx(~nihT;%<","xxi k",
"ya}{xlRMH98-,+~^","yeah o","years e","yesterday|","yo'ySPH=nk","york w9#","you(o\\[YLFEB&&|wutrpdZMG2/)$#vJ95~zgTQ6'7.","youâ€™re.","youngG:5&","your qTDB2~zC@5/.",
"yoursP","youtubeJ$","zapateroX","zenit]","zonaY","zone#","zubiaga_","zucchero*");
var FN=Fs.length, WN=Ws.length, BW=window.opener;
var AR=new Array(FN), AI=new Array(FN), M2=FN>1563;
function Let(c){return c>='a'&&c<='z'||c>='0'&&c<='9'||c>'';}
function Dig(s){
 for(var i=0;i<s.length;++i){
	var c=s.charAt(i);
	if(c>='0'&&c<='9') return 0;
 }
 return 1;
}
function C(l){
 location.href=l;
}
function AW(s){
 var i,n;
 for(i=0;Let(s.charAt(i));++i);
 if(s.charAt(i)==' ') ++i;
 for(var m=1;i<s.length;){
	n=s.charCodeAt(i++)-35;
	if(n<0) n=(n+20)*92+s.charCodeAt(i++)-35;
	else if(M2) n=n*92+s.charCodeAt(i++)-35;
	AI[n]+=m++;
 }
}
function MK(s,n){
 var i;
 for(i=0;i<FN;++i) AI[i]=0;
 s=s.replace(/\*/g,'[^ ]*');
 s=s.replace(/\?/g,'[^ ]');
 s = '^'+s;
 for(i=0;i<WN;++i) if(Ws[i].search(s)==0) AW(Ws[i]);
 for(i=0;i<FN;++i) if(n) AR[i]*=AI[i]; else AR[i]=AI[i];
}
function MT(){
 var c,i,n,t="",ss="",s=document.forms[0].s.value.toLowerCase()+' ';
 for(i=0;i<FN;++i) AR[i]=M;
 for(i=n=0;i<s.length;++i){
	c=s.charAt(i);
	ss+=(c=='<')?"&lt;":c;
	if(Let(c)||c=='*'||c=='?') t+=c;
	else {
		if(t.length>L&&(D||Dig(t))) MK(t,n++);
		t="";
	}
 }
 t='<font color="#ffffff">La búsqueda para</font> "<font color="#00FFFF"><b> '+ss+'</b></font>".<p>\n';
 for(n=0;;++n){
	var m=0,im=-1;
	for(i=0;i<FN;++i) if(AR[i]>m) m=AR[im=i];
	if(im<0){
		if(n==0) t+="<div align=center><p><b>No hay resultados.</b></div><p>\n";
		break;
	}
	AR[im]=0;
	t+=("<b>"+(n+1)+".</b> <a href='javascript:C(\""+Fs[im].fn+"\")'>"+Fs[im].ft+"</a><br>\n"+Fs[im].fd+"<p>\n");
 }
 return t;
}
function NS(){
 if(document.getElementById) document.getElementById('txt').innerHTML=MT();
 else document.forms[0].submit();
 return false;
}
function SS(){
 if(location.search){
	var o="€,??????????????????????????????????????????????????????";
	var t="";
	for(var i=3; i<location.search.length; t+=c) {
		var c=location.search.charAt(i++);
		if(c=='+') c=' ';
		if(c=='%') {
			var v=parseInt(location.search.substring(i,i+2),16);
			if(v<128) c=String.fromCharCode(v);
			else c=o.charAt(v-128);
			i+=2;
		}
	}
	document.forms[0].s.value=t;
 }
}
//-->